// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";
import type { Step } from "./Step";

/**
 * What the cycle position is turned into.
 */
export type Curve = { "Shape": Shape } | { "Steps": Array<Step> };
