// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a running effect came from.
 */
export type EffectSource = "Programmer" | { "Cue": string };
