// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParameterValue = { "type": "Float", "value": number } | { "type": "Int", "value": number } | { "type": "Color", "value": { r: number, g: number, b: number, overrides: { [key in string]?: number }, } } | { "type": "Bool", "value": boolean } | { "type": "Text", "value": string };
