// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";
import type { ParameterValue } from "./ParameterValue";

/**
 * A fade the engine is part way through, described well enough that a node could do
 * it instead.
 *
 * The engine interpolates this itself for everything that cannot be told about time.
 * A node that advertises `transitions` is handed the description and left to it, and
 * the console stops sending samples for that port until the fade is over.
 */
export type RunningFade = { from: ParameterValue, to: ParameterValue, 
/**
 * Console unix ms the movement starts, with any delay already added.
 */
t0: bigint, duration_ms: number, easing: Easing, cue_id: string, };
