// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Curve } from "./Curve";
import type { Direction } from "./Direction";
import type { EffectSource } from "./EffectSource";
import type { ParameterValue } from "./ParameterValue";

/**
 * What is actually running on one fixture parameter: rate resolved to Hz, anchor
 * decided, nothing left to look up.
 *
 * This is the value a capable node is sent, and the value the GUI reads to draw a
 * dot on a waveform. It is LOCAL on the fixture, because it is a description of what
 * this station is currently rendering rather than a fact about the show.
 */
export type RunningEffect = { effect_id: string, curve: Curve, rate_hz: number, low: ParameterValue, high: ParameterValue, width: number, direction: Direction, phase: number, t0: bigint, source: EffectSource, };
