// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five shapes, evaluated over one cycle.
 */
export type Shape = "Sine" | "Triangle" | "Square" | "SawUp" | "SawDown";
