// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";
import type { ParameterValue } from "./ParameterValue";

/**
 * One keyframe of a step list.
 *
 * The value is a real [`ParameterValue`] rather than a level, so a chase can be red,
 * green, blue rather than three brightnesses of one colour. `easing` describes the
 * transition into the *next* step, which is why a hard chase is a list of steps that
 * all say [`Easing::Step`].
 */
export type Step = { 
/**
 * Where in the cycle this step begins, 0..1.
 */
at: number, value: ParameterValue, easing: Easing, };
