use serde::{Deserialize, Serialize};
use ts_rs::TS;
use uuid::Uuid;

use crate::{pult_commands, PultSchema};

// CueAccessor is generated by #[derive(PultSchema)] on Cue in cue.rs.
// It must be in scope here because the generated SequenceAccessor::cues()
// method returns EntityCollectionAccessor<CueAccessor<H>>.
#[allow(unused_imports)]
use super::cue::CueAccessor;

// Commands for Sequence must live here (pult-schema) due to Rust's orphan rule.
// They are registered via inventory and dispatched by the engine through all protocols.
#[pult_commands]
impl Sequence {
    /// Advance to the next cue, staying on the last one when there is no next.
    ///
    /// Running out of cues is not turning the sequence off. A light does not go dark
    /// because the operator pressed Go once more than there were cues, and the way to
    /// say that is to leave the last cue owning what it faded to — rather than to
    /// leave the values behind under a cue marked inactive, which is what wrapping to
    /// `None` used to do. Having only [`Sequence::off`] reach `None` is also what
    /// makes "nothing is driving these parameters any more" a thing playback can see.
    ///
    /// Args: `{ "at": <console unix ms> }`, optional. Every station runs this command
    /// from the same arguments, so carrying the time is what makes all of them anchor
    /// the cue at the same millisecond rather than at whenever each of them got here.
    #[pult_command(args = "{ at?: number }")]
    pub fn go_next(
        &mut self,
        args: serde_json::Value,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let next = self.active_cue_index.map(|i| i + 1).unwrap_or(0);
        if next >= self.cue_ids.len() {
            // Already at the end, or there is nothing to go to at all. Whatever is
            // showing goes on showing, and the anchor is left alone: re-anchoring
            // here would restart the running cue's effects on every press.
            return Ok(());
        }
        self.active_cue_index = Some(next);
        self.went_at = Some(went_at(&args));
        Ok(())
    }

    /// Take the sequence off: no cue of it is active any more.
    ///
    /// The act this console did not have. Everything it was driving and nothing else
    /// is still driving goes to its home value, which playback works out for itself
    /// from the cues — so this command writes one field and every station in the
    /// session arrives at the same rig.
    ///
    /// Carries its time like a Go, so the release fades from the same millisecond
    /// everywhere.
    #[pult_command(args = "{ at?: number }")]
    pub fn off(
        &mut self,
        args: serde_json::Value,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.active_cue_index = None;
        self.went_at = Some(went_at(&args));
        Ok(())
    }

    /// Jump to the cue with the given ID. Args: { "cueId": "<uuid>", "at"?: <ms> }
    #[pult_command(args = "{ cueId: string, at?: number }")]
    pub fn go_to_cue(
        &mut self,
        args: serde_json::Value,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let cue_id: Uuid = serde_json::from_value(args["cueId"].clone())?;
        self.active_cue_index = self.cue_ids.iter().position(|id| *id == cue_id);
        self.went_at = Some(went_at(&args));
        Ok(())
    }
}

/// An ordered list of cues (called a "sequence" by the operator).
#[derive(Debug, Clone, Serialize, Deserialize, TS, PultSchema)]
#[ts(export)]
#[pult(table = "sequences")]
pub struct Sequence {
    #[pult(lifecycle = PERSISTED, primary_key)]
    pub id: Uuid,
    #[pult(lifecycle = PERSISTED)]
    pub name: String,
    /// Ordered list of cue IDs belonging to this sequence.
    #[pult(lifecycle = PERSISTED, collection_of = Cue, ordered)]
    pub cue_ids: Vec<Uuid>,
    /// Index of the currently active cue within cue_ids, if any.
    #[pult(lifecycle = SYNCED)]
    pub active_cue_index: Option<usize>,
    /// Console unix ms the current cue went.
    ///
    /// Fades and effects are both measured from here, which is why it is replicated
    /// rather than kept per station: two consoles rendering the same cue have to
    /// agree on when it started, not merely that it did.
    #[serde(default)]
    #[pult(lifecycle = SYNCED)]
    pub went_at: Option<u64>,
}

/// The `at` a Go was given, or now.
///
/// A station that fires a follow, or an operator pressing Go, supplies the time so
/// every station anchors on the same instant. Nothing supplies it when the command
/// arrives from an older peer or a hand-written API call, and then local now is the
/// best available answer.
fn went_at(args: &serde_json::Value) -> u64 {
    args.get("at").and_then(|v| v.as_u64()).unwrap_or_else(now_ms)
}

/// Console unix ms.
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn a_sequence(cue_ids: Vec<Uuid>) -> Sequence {
        Sequence {
            id: Uuid::new_v4(),
            name: "Act 1".into(),
            cue_ids,
            active_cue_index: None,
            went_at: None,
        }
    }

    /// The reason `at` exists. Every station runs the same command from the same
    /// arguments, so a Go that carries its time anchors the cue at one millisecond
    /// everywhere rather than at whenever each station's actor got round to it.
    #[test]
    fn a_go_that_carries_its_time_anchors_the_cue_there() {
        let mut seq = a_sequence(vec![Uuid::new_v4(), Uuid::new_v4()]);

        seq.go_next(serde_json::json!({ "at": 1_756_550_400_123u64 })).unwrap();
        assert_eq!(seq.active_cue_index, Some(0));
        assert_eq!(seq.went_at, Some(1_756_550_400_123));

        seq.go_next(serde_json::json!({ "at": 1_756_550_403_000u64 })).unwrap();
        assert_eq!(seq.active_cue_index, Some(1));
        assert_eq!(seq.went_at, Some(1_756_550_403_000), "every Go re-anchors");
    }

    /// An older peer, or a hand-written API call, supplies no time. Local now is then
    /// the best available answer, and the stations differ by their clock skew rather
    /// than by nothing at all.
    #[test]
    fn a_go_without_a_time_anchors_now() {
        let mut seq = a_sequence(vec![Uuid::new_v4()]);
        let before = now_ms();

        seq.go_next(serde_json::json!({})).unwrap();

        let at = seq.went_at.expect("anchored regardless");
        assert!(at >= before, "not before the call");
        assert!(at <= now_ms(), "not after it either");
    }

    #[test]
    fn jumping_to_a_cue_anchors_it_the_same_way() {
        let target = Uuid::new_v4();
        let mut seq = a_sequence(vec![Uuid::new_v4(), target]);

        seq.go_to_cue(serde_json::json!({ "cueId": target, "at": 42u64 })).unwrap();
        assert_eq!(seq.active_cue_index, Some(1));
        assert_eq!(seq.went_at, Some(42));
    }

    /// Go at the last cue does nothing at all — not even re-anchor, which would
    /// restart that cue's effects under an operator leaning on the button.
    ///
    /// This is where `None` used to come from, and taking it away is what lets `None`
    /// mean the sequence was turned off.
    #[test]
    fn going_past_the_last_cue_stays_on_it() {
        let mut seq = a_sequence(vec![Uuid::new_v4()]);
        seq.active_cue_index = Some(0);
        seq.went_at = Some(7);

        seq.go_next(serde_json::json!({ "at": 9u64 })).unwrap();

        assert_eq!(seq.active_cue_index, Some(0), "still on the last cue");
        assert_eq!(seq.went_at, Some(7), "and still where it went");
    }

    #[test]
    fn a_sequence_with_no_cues_has_nowhere_to_go() {
        let mut seq = a_sequence(vec![]);

        seq.go_next(serde_json::json!({ "at": 9u64 })).unwrap();

        assert_eq!(seq.active_cue_index, None);
        assert_eq!(seq.went_at, None, "nothing went, so nothing is anchored");
    }

    /// The only way to no active cue, which is what makes it mean something.
    #[test]
    fn taking_a_sequence_off_leaves_no_cue_active() {
        let mut seq = a_sequence(vec![Uuid::new_v4(), Uuid::new_v4()]);
        seq.active_cue_index = Some(1);

        seq.off(serde_json::json!({ "at": 11u64 })).unwrap();

        assert_eq!(seq.active_cue_index, None);
        assert_eq!(seq.went_at, Some(11), "carried, so every station releases from one instant");
    }

    /// SYNCED, and added after showfiles existed, so a sequence written before it
    /// has no key and reads back unanchored.
    #[test]
    fn a_sequence_stored_before_went_at_existed_still_parses() {
        let legacy = serde_json::json!({
            "id": Uuid::nil(),
            "name": "Act 1",
            "cue_ids": [],
            "active_cue_index": null,
        });
        let parsed: Sequence = serde_json::from_value(legacy).unwrap();
        assert_eq!(parsed.went_at, None);
    }
}
