use serde::{Deserialize, Serialize};
use ts_rs::TS;
use uuid::Uuid;

use crate::{pult_commands, PultSchema};

// CueAccessor is generated by #[derive(PultSchema)] on Cue in cue.rs.
// It must be in scope here because the generated SequenceAccessor::cues()
// method returns EntityCollectionAccessor<CueAccessor<H>>.
#[allow(unused_imports)]
use super::cue::CueAccessor;

// Commands for Sequence must live here (pult-schema) due to Rust's orphan rule.
// They are registered via inventory and dispatched by the engine through all protocols.
#[pult_commands]
impl Sequence {
    /// Advance to the next cue, wrapping to None if already at the last.
    #[pult_command]
    pub fn go_next(
        &mut self,
        _args: serde_json::Value,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let next = self.active_cue_index.map(|i| i + 1).unwrap_or(0);
        self.active_cue_index = if next < self.cue_ids.len() { Some(next) } else { None };
        Ok(())
    }

    /// Jump to the cue with the given ID. Args: { "cueId": "<uuid>" }
    #[pult_command]
    pub fn go_to_cue(
        &mut self,
        args: serde_json::Value,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let cue_id: Uuid = serde_json::from_value(args["cueId"].clone())?;
        self.active_cue_index = self.cue_ids.iter().position(|id| *id == cue_id);
        Ok(())
    }
}

/// An ordered list of cues (called a "sequence" by the operator).
#[derive(Debug, Clone, Serialize, Deserialize, TS, PultSchema)]
#[ts(export)]
#[pult(table = "sequences")]
pub struct Sequence {
    #[pult(lifecycle = PERSISTED, primary_key)]
    pub id: Uuid,
    #[pult(lifecycle = PERSISTED)]
    pub name: String,
    /// Ordered list of cue IDs belonging to this sequence.
    #[pult(lifecycle = PERSISTED, collection_of = Cue, ordered)]
    pub cue_ids: Vec<Uuid>,
    /// Index of the currently active cue within cue_ids, if any.
    #[pult(lifecycle = SYNCED)]
    pub active_cue_index: Option<usize>,
}
