use std::{collections::HashMap, env, fs, path::PathBuf, process::Command};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use pult_schema::{commands::CommandRegistration, registry::EntityMeta};

#[derive(Parser)]
#[command(name = "pult-codegen", about = "TypeScript type + SQL migration generation for the-pult")]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate TypeScript types from pult-schema and SQL migrations, write to frontend/ and backend/.
    Generate,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Cmd::Generate => generate(),
    }
}

fn generate() -> Result<()> {
    let workspace = workspace_root().context("could not find workspace root Cargo.toml")?;

    generate_ts_bindings(&workspace)?;
    generate_frontend_proxy(&workspace)?;
    generate_sql_migration(&workspace)?;

    Ok(())
}

fn generate_ts_bindings(workspace: &PathBuf) -> Result<()> {
    let out_dir = workspace.join("frontend/src/lib/generated");
    fs::create_dir_all(&out_dir)?;

    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            fs::remove_file(&path)?;
        }
    }

    eprintln!("Running cargo test -p pult-schema to export TypeScript types...");
    let status = Command::new("cargo")
        .args(["test", "-p", "pult-schema", "--", "--nocapture"])
        .env("TS_RS_EXPORT_DIR", &out_dir)
        .current_dir(workspace)
        .status()
        .context("failed to run `cargo test -p pult-schema`")?;

    if !status.success() {
        anyhow::bail!("`cargo test -p pult-schema` failed — check output above");
    }

    // Write ShowState — root proxy type, mirrors engine::ShowState.
    fs::write(
        out_dir.join("ShowState.ts"),
        concat!(
            "// Auto-generated by pult-codegen — do not edit manually.\n",
            "// Run: cargo run -p pult-codegen -- generate\n",
            "\n",
            "import type { Show } from \"./Show.js\";\n",
            "import type { Sequence } from \"./Sequence.js\";\n",
            "import type { Cue } from \"./Cue.js\";\n",
            "import type { Fixture } from \"./Fixture.js\";\n",
            "\n",
            "/** Root data shape. Mirrors ShowState in pult-backend/src/engine. */\n",
            "export type ShowState = {\n",
            "  show: Show | null;\n",
            "  sequences: Sequence[];\n",
            "  cues: Cue[];\n",
            "  fixtures: Fixture[];\n",
            "};\n",
        ),
    )?;

    let mut modules: Vec<String> = Vec::new();
    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if stem != "index" {
                    modules.push(stem.to_owned());
                }
            }
        }
    }
    modules.sort();

    let mut index = String::from(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n",
    );
    let serde_json_dir = out_dir.join("serde_json");
    if serde_json_dir.join("JsonValue.ts").exists() {
        index.push_str("export type { JsonValue } from \"./serde_json/JsonValue.js\";\n");
    }
    for module in &modules {
        index.push_str(&format!("export * from \"./{module}.js\";\n"));
    }

    let index_path = out_dir.join("index.ts");
    fs::write(&index_path, &index)?;

    eprintln!("✓ Generated {} TypeScript type files → {}", modules.len(), out_dir.display());
    Ok(())
}

fn generate_frontend_proxy(workspace: &PathBuf) -> Result<()> {
    let out_path = workspace.join("frontend/src/lib/ws/data.ts");

    // Collect entities that have a table (excludes purely in-memory types), sorted for determinism.
    let mut entities: Vec<&EntityMeta> = inventory::iter::<EntityMeta>()
        .filter(|m| m.table_name.is_some())
        .collect();
    entities.sort_by_key(|m| m.entity_name);

    // Commands grouped by entity table name, sorted for determinism.
    let mut commands_by_table: HashMap<&str, Vec<&CommandRegistration>> = HashMap::new();
    for cmd in inventory::iter::<CommandRegistration>() {
        commands_by_table.entry((cmd.entity_table)()).or_default().push(cmd);
    }
    for cmds in commands_by_table.values_mut() {
        cmds.sort_by_key(|c| c.command_name);
    }

    let mut out = String::new();
    out.push_str(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n\
         import type { PathProxy, SubscribeOptions } from './proxy.js';\n\
         import type { PultWsClient } from './client.js';\n\
         import { createDataProxy } from './proxy.js';\n",
    );
    for meta in &entities {
        out.push_str(&format!(
            "import type {{ {} }} from '../generated/{}.js';\n",
            meta.entity_name, meta.entity_name,
        ));
    }

    // Entity handles (collections only)
    out.push_str("\n// ── Entity handles ───────────────────────────────────────────────────────────\n\n");
    for meta in &entities {
        if meta.is_singleton { continue; }
        let name = meta.entity_name;
        out.push_str(&format!("export type {}Entity = PathProxy<{}> & {{\n  delete(): Promise<void>;\n", name, name));
        if let Some(cmds) = commands_by_table.get(meta.table_name.unwrap()) {
            for cmd in cmds {
                if cmd.args_ts.is_empty() {
                    out.push_str(&format!("  {}(): Promise<void>;\n", cmd.command_name));
                } else {
                    out.push_str(&format!("  {}(args: {}): Promise<void>;\n", cmd.command_name, cmd.args_ts));
                }
            }
        }
        out.push_str("};\n\n");
    }

    // Collection handles
    out.push_str("// ── Collection handles ──────────────────────────────────────────────────────\n\n");
    for meta in &entities {
        if meta.is_singleton { continue; }
        let n = meta.entity_name;
        out.push_str(&format!("export type {n}Collection = {{\n"));
        out.push_str(&format!("  get(): Promise<{n}[]>;\n"));
        out.push_str(&format!("  set(value: {n}[]): Promise<void>;\n"));
        out.push_str(&format!("  subscribe(cb: (value: {n}[]) => void, opts?: SubscribeOptions): () => void;\n"));
        out.push_str(&format!("  subscribeDeep(cb: (value: {n}[]) => void, opts?: SubscribeOptions): () => void;\n"));
        out.push_str(&format!("  byId(id: string): {n}Entity;\n"));
        out.push_str(&format!("  nth(n: number): {n}Entity;\n"));
        out.push_str(&format!("  create(entity: {n}): Promise<void>;\n"));
        out.push_str(&format!("  [n: number]: {n}Entity;\n"));
        out.push_str("};\n\n");
    }

    // DataRoot
    out.push_str("// ── DataRoot ─────────────────────────────────────────────────────────────────\n\n");
    out.push_str("/** Typed root for the pult:data context. Every field maps to a live path proxy. */\n");
    out.push_str("export type DataRoot = {\n");
    for meta in &entities {
        let table = meta.table_name.unwrap();
        if meta.is_singleton {
            out.push_str(&format!("  {}: PathProxy<{} | null>;\n", table, meta.entity_name));
        } else {
            out.push_str(&format!("  {}: {}Collection;\n", table, meta.entity_name));
        }
    }
    out.push_str("};\n\n");

    out.push_str("/** Create the typed root proxy. The runtime proxy handles all DataRoot operations generically. */\n");
    out.push_str("export function createRootProxy(client: PultWsClient): DataRoot {\n");
    out.push_str("  return createDataProxy(client) as unknown as DataRoot;\n");
    out.push_str("}\n");

    fs::write(&out_path, &out)?;
    eprintln!("✓ Generated frontend proxy types → {}", out_path.display());
    Ok(())
}

fn generate_sql_migration(workspace: &PathBuf) -> Result<()> {
    let migration_path = workspace.join(
        "crates/pult-backend/src/infra/showfile/migrations/001_initial.sql",
    );

    let mut parts: Vec<String> = Vec::new();

    // Collect CREATE TABLE statements from all registered entities
    let mut entity_metas: Vec<&EntityMeta> = inventory::iter::<EntityMeta>().collect();
    // Sort for deterministic output
    entity_metas.sort_by_key(|m| m.entity_name);

    for meta in entity_metas {
        if let Some(sql) = (meta.create_table_sql)() {
            parts.push(sql);
        }
    }

    // The oplog table is infrastructure — not a PultEntity, stays hand-written here.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS oplog (\n",
        "    seq         INTEGER NOT NULL,\n",
        "    node_id     TEXT NOT NULL,\n",
        "    op_id       TEXT NOT NULL,\n",
        "    clock_json  TEXT NOT NULL,\n",
        "    path_json   TEXT NOT NULL,\n",
        "    value_json  TEXT NOT NULL,\n",
        "    lifecycle   TEXT NOT NULL,\n",
        "    timestamp   TEXT NOT NULL,\n",
        "    PRIMARY KEY (node_id, seq)\n",
        ");"
    ).to_string());

    let header = "-- Auto-generated by pult-codegen — do not edit manually.\n\
                  -- Run: cargo run -p pult-codegen -- generate\n\n";
    let content = format!("{}{}", header, parts.join("\n\n"));

    fs::write(&migration_path, &content)?;
    eprintln!("✓ Generated SQL migration → {}", migration_path.display());
    Ok(())
}

fn workspace_root() -> Option<PathBuf> {
    let mut dir = env::current_dir().ok()?;
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            if let Ok(content) = fs::read_to_string(&manifest) {
                if content.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        if !dir.pop() {
            return None;
        }
    }
}
