use std::{collections::HashMap, env, fs, path::{Path, PathBuf}, process::Command};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use pult_schema::{commands::CommandRegistration, registry::EntityMeta};

#[derive(Parser)]
#[command(name = "pult-codegen", about = "TypeScript type + SQL migration generation for the-pult")]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate TypeScript types from pult-schema and SQL migrations, write to frontend/ and backend/.
    Generate,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Cmd::Generate => generate(),
    }
}

fn generate() -> Result<()> {
    let workspace = workspace_root().context("could not find workspace root Cargo.toml")?;

    generate_ts_bindings(&workspace)?;
    generate_frontend_proxy(&workspace)?;
    generate_sql_migration(&workspace)?;

    Ok(())
}

fn generate_ts_bindings(workspace: &PathBuf) -> Result<()> {
    let out_dir = workspace.join("frontend/src/lib/generated");
    fs::create_dir_all(&out_dir)?;

    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            fs::remove_file(&path)?;
        }
    }

    eprintln!("Running cargo test -p pult-schema to export TypeScript types...");
    let status = Command::new("cargo")
        .args(["test", "-p", "pult-schema", "--", "--nocapture"])
        .env("TS_RS_EXPORT_DIR", &out_dir)
        .current_dir(workspace)
        .status()
        .context("failed to run `cargo test -p pult-schema`")?;

    if !status.success() {
        anyhow::bail!("`cargo test -p pult-schema` failed — check output above");
    }

    numbers_not_bigints(&out_dir)?;

    // ShowState mirrors the backend's root state. Built from the registry so a new
    // entity shows up here without an edit.
    let mut show_state = String::from(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n",
    );
    let entities = EntityMeta::all_with_tables();
    for meta in &entities {
        show_state.push_str(&format!(
            "import type {{ {n} }} from \"./{n}.js\";\n",
            n = meta.entity_name,
        ));
    }
    show_state.push_str("\n/** Root data shape. Mirrors ShowState in pult-backend/src/engine. */\n");
    show_state.push_str("export type ShowState = {\n");
    for meta in &entities {
        let table = meta.table_name.unwrap();
        if meta.is_singleton {
            show_state.push_str(&format!("  {table}: {} | null;\n", meta.entity_name));
        } else {
            show_state.push_str(&format!("  {table}: {}[];\n", meta.entity_name));
        }
    }
    show_state.push_str("};\n");
    fs::write(out_dir.join("ShowState.ts"), &show_state)?;

    let mut modules: Vec<String> = Vec::new();
    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if stem != "index" {
                    modules.push(stem.to_owned());
                }
            }
        }
    }
    modules.sort();

    let mut index = String::from(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n",
    );
    let serde_json_dir = out_dir.join("serde_json");
    if serde_json_dir.join("JsonValue.ts").exists() {
        index.push_str("export type { JsonValue } from \"./serde_json/JsonValue.js\";\n");
    }
    for module in &modules {
        index.push_str(&format!("export * from \"./{module}.js\";\n"));
    }

    let index_path = out_dir.join("index.ts");
    fs::write(&index_path, &index)?;

    eprintln!("✓ Generated {} TypeScript type files → {}", modules.len(), out_dir.display());
    Ok(())
}

/// Say `number` where ts-rs said `bigint`.
///
/// ts-rs maps every 64-bit integer to `bigint`, which would be right if the wire
/// were something that could carry one. It is JSON: `serde_json` writes a `u64` as a
/// plain number and `JSON.parse` reads it back as a `number`, so the declared type
/// was a lie about every value that actually arrives — and `count === 0n` is `false`
/// for the `0` that turns up, which is how a working sACN output came to be reported
/// as unhealthy for ever.
///
/// The cost of being honest is that a value beyond 2^53 is not represented exactly.
/// Nothing here counts that high: the largest is a machine's memory in bytes, which
/// runs out of interesting somewhere around a petabyte.
///
/// Done here rather than with `#[ts(type = "number")]` on each field, because that
/// is a thing to remember every time somebody writes `u64` — and forgetting it looks
/// like this bug rather than like a compile error.
fn numbers_not_bigints(dir: &Path) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        // ts-rs nests what it exports for other crates, `serde_json` among them.
        if path.is_dir() {
            numbers_not_bigints(&path)?;
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("ts") {
            continue;
        }
        let source = fs::read_to_string(&path)?;
        let rewritten = replace_word(&source, "bigint", "number");
        if rewritten != source {
            fs::write(&path, rewritten)?;
        }
    }
    Ok(())
}

/// Replace whole identifiers only, so `bigint` inside a longer word is left alone.
fn replace_word(source: &str, word: &str, with: &str) -> String {
    let ident = |c: char| c.is_alphanumeric() || c == '_' || c == '$';
    let mut out = String::with_capacity(source.len());
    let mut rest = source;
    while let Some(at) = rest.find(word) {
        let before_ok = rest[..at].chars().next_back().is_none_or(|c| !ident(c));
        let after = &rest[at + word.len()..];
        let after_ok = after.chars().next().is_none_or(|c| !ident(c));
        out.push_str(&rest[..at]);
        out.push_str(if before_ok && after_ok { with } else { word });
        rest = after;
    }
    out.push_str(rest);
    out
}

fn generate_frontend_proxy(workspace: &PathBuf) -> Result<()> {
    let out_path = workspace.join("frontend/src/lib/ws/data.ts");

    // Collect entities that have a table (excludes purely in-memory types), sorted for determinism.
    let mut entities: Vec<&EntityMeta> = inventory::iter::<EntityMeta>()
        .filter(|m| m.table_name.is_some())
        .collect();
    entities.sort_by_key(|m| m.entity_name);

    // Commands grouped by entity table name, sorted for determinism.
    let mut commands_by_table: HashMap<&str, Vec<&CommandRegistration>> = HashMap::new();
    for cmd in inventory::iter::<CommandRegistration>() {
        commands_by_table.entry((cmd.entity_table)()).or_default().push(cmd);
    }
    for cmds in commands_by_table.values_mut() {
        cmds.sort_by_key(|c| c.command_name);
    }

    let mut out = String::new();
    out.push_str(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n\
         import type { PathProxy, SubscribeOptions } from './proxy.js';\n\
         import type { PultWsClient } from './client.js';\n\
         import { createDataProxy } from './proxy.js';\n",
    );
    for meta in &entities {
        out.push_str(&format!(
            "import type {{ {} }} from '../generated/{}.js';\n",
            meta.entity_name, meta.entity_name,
        ));
    }

    // Entity handles (collections only)
    out.push_str("\n// ── Entity handles ───────────────────────────────────────────────────────────\n\n");
    for meta in &entities {
        if meta.is_singleton { continue; }
        let name = meta.entity_name;
        out.push_str(&format!("export type {}Entity = PathProxy<{}> & {{\n  delete(): Promise<void>;\n", name, name));
        if let Some(cmds) = commands_by_table.get(meta.table_name.unwrap()) {
            for cmd in cmds {
                if cmd.args_ts.is_empty() {
                    out.push_str(&format!("  {}(): Promise<void>;\n", cmd.command_name));
                } else {
                    out.push_str(&format!("  {}(args: {}): Promise<void>;\n", cmd.command_name, cmd.args_ts));
                }
            }
        }
        out.push_str("};\n\n");
    }

    // Collection handles
    out.push_str("// ── Collection handles ──────────────────────────────────────────────────────\n\n");
    for meta in &entities {
        if meta.is_singleton { continue; }
        let n = meta.entity_name;
        out.push_str(&format!("export type {n}Collection = {{\n"));
        out.push_str(&format!("  get(): Promise<{n}[]>;\n"));
        out.push_str(&format!("  set(value: {n}[]): Promise<void>;\n"));
        out.push_str(&format!("  subscribe(cb: (value: {n}[]) => void, opts?: SubscribeOptions): () => void;\n"));
        out.push_str(&format!("  subscribeDeep(cb: (value: {n}[]) => void, opts?: SubscribeOptions): () => void;\n"));
        out.push_str(&format!("  byId(id: string): {n}Entity;\n"));
        out.push_str(&format!("  nth(n: number): {n}Entity;\n"));
        out.push_str(&format!("  create(entity: {n}): Promise<void>;\n"));
        // The collection verbs the runtime proxy answers everywhere. Only
        // `programmer_values` does anything with `home`, and only `fixtures` with
        // `takeHome`; the station refuses each elsewhere, naming the path, the same
        // way `by` refuses a field that is not a number. Written for every collection
        // rather than for one, because this file is generated from the registry and
        // must not know a table by name.
        out.push_str("  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;\n");
        out.push_str("  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;\n");
        out.push_str(&format!("  [n: number]: {n}Entity;\n"));
        out.push_str("};\n\n");
    }

    // DataRoot
    out.push_str("// ── DataRoot ─────────────────────────────────────────────────────────────────\n\n");
    out.push_str("/** Typed root for the pult:data context. Every field maps to a live path proxy. */\n");
    out.push_str("export type DataRoot = {\n");
    for meta in &entities {
        let table = meta.table_name.unwrap();
        if meta.is_singleton {
            out.push_str(&format!("  {}: PathProxy<{} | null>;\n", table, meta.entity_name));
        } else {
            out.push_str(&format!("  {}: {}Collection;\n", table, meta.entity_name));
        }
    }
    out.push_str("};\n\n");

    out.push_str("/** Create the typed root proxy. The runtime proxy handles all DataRoot operations generically. */\n");
    out.push_str("export function createRootProxy(client: PultWsClient): DataRoot {\n");
    out.push_str("  return createDataProxy(client) as unknown as DataRoot;\n");
    out.push_str("}\n");

    fs::write(&out_path, &out)?;
    eprintln!("✓ Generated frontend proxy types → {}", out_path.display());
    Ok(())
}

fn generate_sql_migration(workspace: &PathBuf) -> Result<()> {
    let migration_path = workspace.join(
        "crates/pult-backend/src/infra/showfile/migrations/001_initial.sql",
    );

    let mut parts: Vec<String> = Vec::new();

    // Collect CREATE TABLE statements from all registered entities
    let mut entity_metas: Vec<&EntityMeta> = inventory::iter::<EntityMeta>().collect();
    // Sort for deterministic output
    entity_metas.sort_by_key(|m| m.entity_name);

    for meta in entity_metas {
        if let Some(sql) = (meta.create_table_sql)() {
            parts.push(sql);
        }
    }

    // Collection display order. Infrastructure rather than a PultEntity: it is one
    // row per entity across every table, so it cannot be derived from any one of them.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS collection_order (\n",
        "    table_name TEXT NOT NULL,\n",
        "    entity_id  TEXT NOT NULL,\n",
        "    position   INTEGER NOT NULL,\n",
        "    PRIMARY KEY (table_name, entity_id)\n",
        ");"
    ).to_string());

    // The oplog table is infrastructure — not a PultEntity, stays hand-written here.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS oplog (\n",
        "    seq         INTEGER NOT NULL,\n",
        "    node_id     TEXT NOT NULL,\n",
        "    op_id       TEXT NOT NULL,\n",
        "    clock_json  TEXT NOT NULL,\n",
        "    path_json   TEXT NOT NULL,\n",
        "    value_json  TEXT NOT NULL,\n",
        "    lifecycle   TEXT NOT NULL,\n",
        "    timestamp   TEXT NOT NULL,\n",
        // Who asked, what was there before, which gesture this write was part of,
        // and which gesture it reverses. All nullable: the engine's own writes have
        // no author, an operation logged before undo existed captured nothing to put
        // back, and most writes are not part of a gesture and reverse nothing.
        "    user_id     TEXT,\n",
        "    previous_json TEXT,\n",
        "    undoes      TEXT,\n",
        "    gesture     TEXT,\n",
        "    PRIMARY KEY (node_id, seq)\n",
        ");"
    ).to_string());

    // What the history panel and undo ask for: the newest rows somebody authored.
    // Without this the query behind every Ctrl-Z scans a log that is now pruned but
    // still long, and the retention delete that keeps it short scans it too.
    parts.push(concat!(
        "CREATE INDEX IF NOT EXISTS oplog_by_people\n",
        "    ON oplog (user_id, timestamp DESC, seq DESC);"
    ).to_string());

    // How far this station has pruned, per node whose operations it cut.
    //
    // Not show data and never replicated: two stations legitimately hold different
    // amounts of history, and one station's disk pressure is not everyone's lost
    // history. It is a fact about *this copy* of the log, so it lives beside it.
    //
    // Per originating node rather than one number, because catch-up compares a peer's
    // vector clock entry for the node that wrote a row. "Everything up to here is
    // gone" is only meaningful about one node's sequence.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS oplog_floor (\n",
        "    node_id           TEXT NOT NULL PRIMARY KEY,\n",
        // Every operation from this node at or below this seq has been deleted, so a
        // peer that has not reached it cannot be caught up from what is left and is
        // sent a snapshot instead.
        "    pruned_through_seq INTEGER NOT NULL\n",
        ");"
    ).to_string());

    // Assets are bytes, not entity fields: a stage plan is a few megabytes and has
    // no business in the oplog. Content-addressed, so the id is the check.
    //
    // The metadata only. The bytes are files in the bundle's `assets/` directory,
    // because a version snapshot is a copy of this file and one that carried the
    // rig's whole mesh library would cost that per save.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS assets (\n",
        "    sha256     TEXT NOT NULL PRIMARY KEY,\n",
        "    mime       TEXT NOT NULL,\n",
        "    byte_len   INTEGER NOT NULL,\n",
        "    created_at TEXT NOT NULL\n",
        ");"
    ).to_string());

    let header = "-- Auto-generated by pult-codegen — do not edit manually.\n\
                  -- Run: cargo run -p pult-codegen -- generate\n\n";
    let content = format!("{}{}", header, parts.join("\n\n"));

    fs::write(&migration_path, &content)?;
    eprintln!("✓ Generated SQL migration → {}", migration_path.display());
    Ok(())
}

fn workspace_root() -> Option<PathBuf> {
    let mut dir = env::current_dir().ok()?;
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            if let Ok(content) = fs::read_to_string(&manifest) {
                if content.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        if !dir.pop() {
            return None;
        }
    }
}
