use std::{env, fs, path::PathBuf, process::Command};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use pult_schema::registry::EntityMeta;

#[derive(Parser)]
#[command(name = "pult-codegen", about = "TypeScript type + SQL migration generation for the-pult")]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate TypeScript types from pult-schema and SQL migrations, write to frontend/ and backend/.
    Generate,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Cmd::Generate => generate(),
    }
}

fn generate() -> Result<()> {
    let workspace = workspace_root().context("could not find workspace root Cargo.toml")?;

    generate_ts_bindings(&workspace)?;
    generate_sql_migration(&workspace)?;

    Ok(())
}

fn generate_ts_bindings(workspace: &PathBuf) -> Result<()> {
    let out_dir = workspace.join("frontend/src/lib/generated");
    fs::create_dir_all(&out_dir)?;

    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            fs::remove_file(&path)?;
        }
    }

    eprintln!("Running cargo test -p pult-schema to export TypeScript types...");
    let status = Command::new("cargo")
        .args(["test", "-p", "pult-schema", "--", "--nocapture"])
        .env("TS_RS_EXPORT_DIR", &out_dir)
        .current_dir(workspace)
        .status()
        .context("failed to run `cargo test -p pult-schema`")?;

    if !status.success() {
        anyhow::bail!("`cargo test -p pult-schema` failed — check output above");
    }

    let mut modules: Vec<String> = Vec::new();
    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "ts") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if stem != "index" {
                    modules.push(stem.to_owned());
                }
            }
        }
    }
    modules.sort();

    let mut index = String::from(
        "// Auto-generated by pult-codegen — do not edit manually.\n\
         // Run: cargo run -p pult-codegen -- generate\n\n",
    );
    let serde_json_dir = out_dir.join("serde_json");
    if serde_json_dir.join("JsonValue.ts").exists() {
        index.push_str("export type { JsonValue } from \"./serde_json/JsonValue.js\";\n");
    }
    for module in &modules {
        index.push_str(&format!("export * from \"./{module}.js\";\n"));
    }

    let index_path = out_dir.join("index.ts");
    fs::write(&index_path, &index)?;

    eprintln!("✓ Generated {} TypeScript type files → {}", modules.len(), out_dir.display());
    Ok(())
}

fn generate_sql_migration(workspace: &PathBuf) -> Result<()> {
    let migration_path = workspace.join(
        "crates/pult-backend/src/infra/showfile/migrations/001_initial.sql",
    );

    let mut parts: Vec<String> = Vec::new();

    // Collect CREATE TABLE statements from all registered entities
    let mut entity_metas: Vec<&EntityMeta> = inventory::iter::<EntityMeta>().collect();
    // Sort for deterministic output
    entity_metas.sort_by_key(|m| m.entity_name);

    for meta in entity_metas {
        if let Some(sql) = (meta.create_table_sql)() {
            parts.push(sql);
        }
    }

    // The oplog table is infrastructure — not a PultEntity, stays hand-written here.
    parts.push(concat!(
        "CREATE TABLE IF NOT EXISTS oplog (\n",
        "    seq         INTEGER NOT NULL,\n",
        "    node_id     TEXT NOT NULL,\n",
        "    op_id       TEXT NOT NULL,\n",
        "    clock_json  TEXT NOT NULL,\n",
        "    path_json   TEXT NOT NULL,\n",
        "    value_json  TEXT NOT NULL,\n",
        "    lifecycle   TEXT NOT NULL,\n",
        "    timestamp   TEXT NOT NULL,\n",
        "    PRIMARY KEY (node_id, seq)\n",
        ");"
    ).to_string());

    let header = "-- Auto-generated by pult-codegen — do not edit manually.\n\
                  -- Run: cargo run -p pult-codegen -- generate\n\n";
    let content = format!("{}{}", header, parts.join("\n\n"));

    fs::write(&migration_path, &content)?;
    eprintln!("✓ Generated SQL migration → {}", migration_path.display());
    Ok(())
}

fn workspace_root() -> Option<PathBuf> {
    let mut dir = env::current_dir().ok()?;
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            if let Ok(content) = fs::read_to_string(&manifest) {
                if content.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        if !dir.pop() {
            return None;
        }
    }
}
