//! The plugin SDK's typed half, generated from the same inventories the frontend
//! proxy comes from.
//!
//! # Why the SDK and not the WIT
//!
//! A component's imports carry the package version, and a record type's fields are
//! part of every signature that uses it, so a `Cue` gaining a field would be a
//! breaking ABI change — and a show now carries its plugins between machines, so a
//! bundle built against schema-of-Tuesday would refuse to load on a station from
//! schema-of-Wednesday. Task 35 wrote that down and it has not changed. So the wire
//! stays `data.set(path, json)` for ever, and the typing is a *source* convenience
//! that compiles away: the worst a plugin built against a newer schema can do is name
//! a path this station does not have, which is the per-path runtime error the
//! frontend has always had.
//!
//! # Two halves, for the same reason the frontend has two
//!
//! `schema.rs` is the entity types, and `data.rs` is the accessors over them —
//! `frontend/src/lib/generated/*.ts` and `frontend/src/lib/ws/data.ts` exactly.
//!
//! The types are a *mirror*, transformed out of the Rust that defines them, because
//! the plugins workspace cannot depend on `pult-schema`: sqlx, tokio and inventory do
//! not go to `wasm32-wasip2`, which is the same wall `pult-render` exists on the far
//! side of. `pult-render` itself is a path dependency rather than mirrored — it was
//! built to be compiled twice and its own crate doc says "and its plugins", so
//! `ParameterValue` in a plugin is the console's `ParameterValue` and not a copy of
//! it.
//!
//! # What reflection there is
//!
//! `EntityMeta` carries field *names* and lifecycles, not shapes, so the field types
//! are read off the schema's own source with `syn`. That is the whole of it: the set
//! of entities, their tables and their commands come from the inventories like
//! everything else here, and only "what type is `Cue::captures`" comes from the file.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use proc_macro2::TokenStream;
use pult_schema::{commands::CommandRegistration, registry::EntityMeta};
use quote::{format_ident, quote};
use syn::{
    punctuated::Punctuated, Attribute, Fields, GenericArgument, Item, Meta, PathArguments, Token,
    Type,
};

const HEADER: &str = "// Auto-generated by pult-codegen — do not edit manually.\n\
                      // Run: cargo run -p pult-codegen -- generate\n\n";

/// Everything the generated SDK spells as itself. Anything else a field mentions
/// becomes `serde_json::Value` and is named in the run's output, so a type that grew
/// out of reach is visible rather than silently untyped.
const PRIMITIVES: &[&str] = &[
    "bool", "char", "f32", "f64", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32",
    "u64", "u128", "usize", "String", "Uuid", "Value",
];

/// Containers whose *arguments* are rewritten and which are otherwise left alone.
const CONTAINERS: &[&str] = &["Option", "Vec", "Box", "HashMap", "BTreeMap", "HashSet", "BTreeSet"];

/// Rust's own words, so a field called `type` or `move` still gets a method.
const KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
    "where", "while",
];

// ── The schema's source, read ─────────────────────────────────────────────────

struct Source {
    /// Every `pub struct` and `pub enum` in `pult-schema`'s `types/`, by name.
    items: BTreeMap<String, Item>,
    /// What `types/` re-exports from `pult-render`, with the module it came from —
    /// these are not mirrored, they are the same types.
    from_render: BTreeMap<String, String>,
}

impl Source {
    /// `types/` is where the show's shapes live; `events/` is where two of them —
    /// a node's id and a vector clock — are defined, because an `outputs` row names
    /// the station that owns it.
    fn read(dirs: &[PathBuf]) -> Result<Self> {
        let mut items = BTreeMap::new();
        let mut from_render = BTreeMap::new();

        let mut paths: Vec<PathBuf> = Vec::new();
        for dir in dirs {
            let mut here: Vec<PathBuf> = fs::read_dir(dir)
                .with_context(|| format!("reading {}", dir.display()))?
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("rs"))
                .collect();
            paths.append(&mut here);
        }
        paths.sort();

        for path in paths {
            let text = fs::read_to_string(&path)?;
            let file = syn::parse_file(&text)
                .with_context(|| format!("parsing {}", path.display()))?;
            for item in file.items {
                match &item {
                    Item::Struct(s) if matches!(s.vis, syn::Visibility::Public(_)) => {
                        items.insert(s.ident.to_string(), item);
                    }
                    Item::Enum(e) if matches!(e.vis, syn::Visibility::Public(_)) => {
                        items.insert(e.ident.to_string(), item);
                    }
                    Item::Use(u) if matches!(u.vis, syn::Visibility::Public(_)) => {
                        collect_render_reexports(&u.tree, &mut Vec::new(), &mut from_render);
                    }
                    _ => {}
                }
            }
        }
        Ok(Source { items, from_render })
    }

    fn knows(&self, name: &str) -> bool {
        self.items.contains_key(name) || self.from_render.contains_key(name)
    }
}

/// `pub use pult_render::effect::{Curve, Easing};` → `Curve → effect`, `Easing → effect`.
fn collect_render_reexports(
    tree: &syn::UseTree,
    prefix: &mut Vec<String>,
    out: &mut BTreeMap<String, String>,
) {
    match tree {
        syn::UseTree::Path(p) => {
            prefix.push(p.ident.to_string());
            collect_render_reexports(&p.tree, prefix, out);
            prefix.pop();
        }
        syn::UseTree::Group(g) => {
            for tree in &g.items {
                collect_render_reexports(tree, prefix, out);
            }
        }
        syn::UseTree::Name(n) => {
            if prefix.first().map(String::as_str) == Some("pult_render") {
                let module = prefix.get(1).cloned().unwrap_or_default();
                out.insert(n.ident.to_string(), module);
            }
        }
        _ => {}
    }
}

// ── Which types are reachable ─────────────────────────────────────────────────

/// Everything an entity's fields can lead to, transitively.
///
/// The set is walked rather than "every type in `types/`" because half of what lives
/// there is not show data at all — a wire viewer's `UniverseFrame`, a helper with a
/// lifetime on it — and a plugin has no path that reaches one.
fn reachable(source: &Source, roots: &[&str]) -> BTreeSet<String> {
    let mut seen = BTreeSet::new();
    let mut queue: Vec<String> = roots.iter().map(|r| r.to_string()).collect();
    while let Some(name) = queue.pop() {
        if !seen.insert(name.clone()) {
            continue;
        }
        let Some(item) = source.items.get(&name) else { continue };
        let mut mentioned = Vec::new();
        match item {
            Item::Struct(s) => {
                for field in &s.fields {
                    mentions(&field.ty, &mut mentioned);
                }
            }
            Item::Enum(e) => {
                for variant in &e.variants {
                    for field in &variant.fields {
                        mentions(&field.ty, &mut mentioned);
                    }
                }
            }
            _ => {}
        }
        for name in mentioned {
            // `knows` and not `items`: what `types/` re-exports from `pult-render` is
            // wanted too, so the mirror can re-export it in turn rather than name a
            // type nothing in the SDK has heard of.
            if source.knows(&name) && !seen.contains(&name) {
                queue.push(name);
            }
        }
    }
    seen
}

/// Every type name a type mentions, container arguments included.
fn mentions(ty: &Type, out: &mut Vec<String>) {
    match ty {
        Type::Path(p) => {
            for segment in &p.path.segments {
                out.push(segment.ident.to_string());
                if let PathArguments::AngleBracketed(args) = &segment.arguments {
                    for arg in &args.args {
                        if let GenericArgument::Type(ty) = arg {
                            mentions(ty, out);
                        }
                    }
                }
            }
        }
        Type::Tuple(t) => t.elems.iter().for_each(|ty| mentions(ty, out)),
        Type::Array(a) => mentions(&a.elem, out),
        Type::Reference(r) => mentions(&r.elem, out),
        _ => {}
    }
}

// ── Which types can still be `Default` ────────────────────────────────────────

/// The named type a field is *directly*, or `None` where a container stands between.
///
/// `Option<Transform>` and `Vec<Transform>` are `Default` whatever `Transform` is;
/// a bare `Transform` is not.
fn direct_named(ty: &Type) -> Option<String> {
    let Type::Path(p) = ty else { return None };
    let last = p.path.segments.last()?;
    let name = last.ident.to_string();
    if CONTAINERS.contains(&name.as_str()) {
        return None;
    }
    Some(name)
}

fn derives(attrs: &[Attribute], wanted: &str) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("derive")
            && attr
                .parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)
                .is_ok_and(|metas| metas.iter().any(|m| m.path().is_ident(wanted)))
    })
}

/// Which mirrored types can carry `#[derive(Default)]`.
///
/// A handful of the schema's types write their `Default` by hand — `Transform` rests
/// at scale 1 and not at scale 0, `FixtureAddress` at universe 1 channel 1 — and an
/// impl is code, which a mirror of the *shapes* has no way to carry. So the mirror
/// drops `Default` for those and, by this fixpoint, for everything holding one
/// directly. Losing the derive is a compile error at the plugin author's desk; keeping
/// it would have been a fixture patched at scale zero, which is not.
fn defaultable(source: &Source, wanted: &BTreeSet<String>) -> BTreeSet<String> {
    let mut yes: BTreeSet<String> = wanted
        .iter()
        .filter(|name| match source.items.get(*name) {
            Some(Item::Struct(s)) => derives(&s.attrs, "Default"),
            Some(Item::Enum(e)) => derives(&e.attrs, "Default"),
            _ => false,
        })
        .cloned()
        .collect();

    loop {
        let mut lost: Vec<String> = Vec::new();
        for name in &yes {
            let mut field_types: Vec<&Type> = Vec::new();
            match source.items.get(name) {
                Some(Item::Struct(s)) => field_types.extend(s.fields.iter().map(|f| &f.ty)),
                Some(Item::Enum(e)) => {
                    for variant in &e.variants {
                        field_types.extend(variant.fields.iter().map(|f| &f.ty));
                    }
                }
                _ => {}
            }
            let holds_one = field_types.iter().filter_map(|ty| direct_named(ty)).any(|held| {
                source.items.contains_key(&held) && !yes.contains(&held)
            });
            if holds_one {
                lost.push(name.clone());
            }
        }
        if lost.is_empty() {
            return yes;
        }
        for name in lost {
            yes.remove(&name);
        }
    }
}

// ── Types, rewritten ──────────────────────────────────────────────────────────

/// The type as the SDK spells it.
///
/// A named type the mirror carries keeps its name; a container is rewritten through;
/// `DateTime<Utc>` becomes [`Timestamp`], which is what the wire has always carried
/// it as; and anything else becomes `serde_json::Value` and is reported.
fn rewrite(ty: &Type, source: &Source, unknown: &mut BTreeSet<String>) -> TokenStream {
    match ty {
        Type::Path(p) => {
            let Some(last) = p.path.segments.last() else { return quote!(serde_json::Value) };
            let name = last.ident.to_string();
            if name == "DateTime" {
                return quote!(Timestamp);
            }
            if name == "Value" {
                return quote!(serde_json::Value);
            }
            let ident = format_ident!("{}", name);
            if CONTAINERS.contains(&name.as_str()) {
                if let PathArguments::AngleBracketed(args) = &last.arguments {
                    let args: Vec<TokenStream> = args
                        .args
                        .iter()
                        .map(|arg| match arg {
                            GenericArgument::Type(ty) => rewrite(ty, source, unknown),
                            other => quote!(#other),
                        })
                        .collect();
                    return quote!(#ident<#(#args),*>);
                }
                return quote!(#ident);
            }
            if PRIMITIVES.contains(&name.as_str()) || source.knows(&name) {
                return quote!(#ident);
            }
            unknown.insert(name);
            quote!(serde_json::Value)
        }
        Type::Tuple(t) => {
            let elems: Vec<TokenStream> =
                t.elems.iter().map(|ty| rewrite(ty, source, unknown)).collect();
            quote!((#(#elems),*))
        }
        Type::Array(a) => {
            let elem = rewrite(&a.elem, source, unknown);
            let len = &a.len;
            quote!([#elem; #len])
        }
        other => {
            unknown.insert(quote!(#other).to_string());
            quote!(serde_json::Value)
        }
    }
}

// ── Attributes, filtered ──────────────────────────────────────────────────────

/// What survives into the mirror: the prose, and what serde does with the field.
///
/// `#[ts(…)]` and `#[pult(…)]` are for tools that are not here. `#[serde(default =
/// "some_fn")]` becomes a plain `#[serde(default)]`, because the function that
/// computes the station's default is a private item of the schema and copying it
/// would mean copying whatever it reads. The difference is only visible for a key
/// that is *absent*, and the station serializes every field it has.
/// A field's attributes, minus a `#[serde(default)]` its own type cannot answer.
///
/// Only reachable for a key that is *absent*, and the station serializes every field
/// it has — so what this gives up is a shape no station writes, and what it buys is a
/// mirror that compiles.
fn field_attrs(
    attrs: &[Attribute],
    ty: &Type,
    source: &Source,
    defaults: &BTreeSet<String>,
) -> Vec<TokenStream> {
    let answerable = direct_named(ty)
        .map(|name| !source.items.contains_key(&name) || defaults.contains(&name))
        .unwrap_or(true);
    keep_attrs(attrs)
        .into_iter()
        .filter(|attr| answerable || attr.to_string() != "# [serde (default)]")
        .collect()
}

fn doc_attrs(attrs: &[Attribute]) -> Vec<TokenStream> {
    attrs.iter().filter(|a| a.path().is_ident("doc")).map(|a| quote!(#a)).collect()
}

fn serde_attrs(attrs: &[Attribute]) -> Vec<TokenStream> {
    keep_attrs(attrs).into_iter().filter(|a| !a.to_string().starts_with("# [doc")).collect()
}

fn keep_attrs(attrs: &[Attribute]) -> Vec<TokenStream> {
    let mut out = Vec::new();
    for attr in attrs {
        let path = attr.path();
        if path.is_ident("doc") || path.is_ident("default") {
            out.push(quote!(#attr));
            continue;
        }
        if !path.is_ident("serde") {
            continue;
        }
        let Ok(metas) = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)
        else {
            out.push(quote!(#attr));
            continue;
        };
        let rewritten: Vec<TokenStream> = metas
            .iter()
            .map(|meta| match meta {
                Meta::NameValue(nv) if nv.path.is_ident("default") => quote!(default),
                other => quote!(#other),
            })
            .collect();
        out.push(quote!(#[serde(#(#rewritten),*)]));
    }
    out
}

/// The derives the mirror carries: what the original had, minus the ones that belong
/// to the console. `Serialize` and `Deserialize` are always on — a type that reaches a
/// plugin at all reaches it as JSON.
fn keep_derives(attrs: &[Attribute], default_ok: bool) -> TokenStream {
    const KEPT: &[&str] = &["Debug", "Clone", "Copy", "PartialEq", "Eq", "Hash", "Default"];
    let mut kept: Vec<String> = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let Ok(metas) = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)
        else {
            continue;
        };
        for meta in metas {
            if let Some(ident) = meta.path().get_ident() {
                let name = ident.to_string();
                if name == "Default" && !default_ok {
                    continue;
                }
                if KEPT.contains(&name.as_str()) && !kept.contains(&name) {
                    kept.push(name);
                }
            }
        }
    }
    let idents: Vec<syn::Ident> = kept.iter().map(|n| format_ident!("{}", n)).collect();
    quote!(#[derive(#(#idents,)* serde::Serialize, serde::Deserialize)])
}

// ── schema.rs ─────────────────────────────────────────────────────────────────

fn render_schema(source: &Source, wanted: &BTreeSet<String>) -> Result<(String, BTreeSet<String>)> {
    let mut unknown = BTreeSet::new();
    let defaults = defaultable(source, wanted);
    let mut items: Vec<TokenStream> = Vec::new();

    // What comes from the evaluator comes from the evaluator. `pult-render` is a path
    // dependency of this workspace precisely so a plugin and the station agree about
    // what a parameter value *is* rather than about what it looks like in JSON.
    let mut by_module: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (name, module) in &source.from_render {
        if wanted.contains(name) {
            by_module.entry(module.as_str()).or_default().push(name.as_str());
        }
    }
    for (module, names) in by_module {
        let module = format_ident!("{}", module);
        let names: Vec<syn::Ident> = names.iter().map(|n| format_ident!("{}", n)).collect();
        items.push(quote! {
            pub use pult_render::#module::{#(#names),*};
        });
    }

    for name in wanted {
        let Some(item) = source.items.get(name) else { continue };
        match item {
            Item::Struct(s) => {
                let ident = &s.ident;
                let doc = doc_attrs(&s.attrs);
                let attrs = serde_attrs(&s.attrs);
                let derives = keep_derives(&s.attrs, defaults.contains(name));
                let body = match &s.fields {
                    Fields::Named(named) => {
                        let fields: Vec<TokenStream> = named
                            .named
                            .iter()
                            .map(|f| {
                                let ident = f.ident.as_ref().unwrap();
                                let attrs = field_attrs(&f.attrs, &f.ty, source, &defaults);
                                let ty = rewrite(&f.ty, source, &mut unknown);
                                quote! { #(#attrs)* pub #ident: #ty, }
                            })
                            .collect();
                        quote!({ #(#fields)* })
                    }
                    // A newtype is how the schema says "this string is a node's id
                    // and not any string", and the mirror keeps that distinction.
                    Fields::Unnamed(unnamed) => {
                        let fields: Vec<TokenStream> = unnamed
                            .unnamed
                            .iter()
                            .map(|f| {
                                let ty = rewrite(&f.ty, source, &mut unknown);
                                quote! { pub #ty }
                            })
                            .collect();
                        quote!((#(#fields),*);)
                    }
                    Fields::Unit => quote!(;),
                };
                items.push(quote! {
                    #(#doc)*
                    #derives
                    #(#attrs)*
                    pub struct #ident #body
                });
            }
            Item::Enum(e) => {
                let ident = &e.ident;
                let doc = doc_attrs(&e.attrs);
                let attrs = serde_attrs(&e.attrs);
                let derives = keep_derives(&e.attrs, defaults.contains(name));
                let variants: Vec<TokenStream> = e
                    .variants
                    .iter()
                    .map(|v| {
                        let ident = &v.ident;
                        let attrs = keep_attrs(&v.attrs);
                        let body = match &v.fields {
                            Fields::Unit => quote!(),
                            Fields::Named(named) => {
                                let fields: Vec<TokenStream> = named
                                    .named
                                    .iter()
                                    .map(|f| {
                                        let ident = f.ident.as_ref().unwrap();
                                        let attrs = field_attrs(&f.attrs, &f.ty, source, &defaults);
                                        let ty = rewrite(&f.ty, source, &mut unknown);
                                        quote! { #(#attrs)* #ident: #ty, }
                                    })
                                    .collect();
                                quote!({ #(#fields)* })
                            }
                            Fields::Unnamed(unnamed) => {
                                let fields: Vec<TokenStream> = unnamed
                                    .unnamed
                                    .iter()
                                    .map(|f| rewrite(&f.ty, source, &mut unknown))
                                    .collect();
                                quote!((#(#fields),*))
                            }
                        };
                        quote! { #(#attrs)* #ident #body, }
                    })
                    .collect();
                items.push(quote! {
                    #(#doc)*
                    #derives
                    #(#attrs)*
                    pub enum #ident { #(#variants)* }
                });
            }
            _ => {}
        }
    }

    let file: syn::File = syn::parse2(quote! {
        //! The show's types, as a plugin sees them.
        //!
        //! A mirror of `pult-schema`'s entity types, transformed out of the Rust that
        //! defines them. It is a mirror rather than a dependency because the plugins
        //! workspace compiles to `wasm32-wasip2` and `pult-schema` carries sqlx,
        //! tokio and inventory — the same wall `pult-render` was split out over.
        //! `pult-render`'s own types are re-exported here rather than copied, since
        //! that crate was built to be compiled twice.
        //!
        //! What a plugin holds is therefore the *shape* the station serializes, not
        //! the station's own struct: methods, invariants and `Default` impls stay
        //! where the console keeps them.

        use std::collections::HashMap;
        use uuid::Uuid;

        /// A moment, RFC 3339, exactly as the wire carries it.
        ///
        /// `chrono::DateTime<Utc>` on the station. A string here, because a plugin
        /// that reads one is passing it back or showing it, and a date library in
        /// every guest is weight for nothing.
        pub type Timestamp = String;

        #(#items)*
    })
    .context("the generated schema mirror is not valid Rust")?;

    Ok((format!("{HEADER}{}", spaced(&prettyplease::unparse(&file))), unknown))
}

/// A blank line between top-level items.
///
/// prettyplease packs them, which is right for a compiler and hard for a person, and
/// this file is meant to be read — a plugin author looking up what a `Cue` carries
/// reads it rather than the schema's own source.
fn spaced(source: &str) -> String {
    let mut out: Vec<&str> = Vec::new();
    for line in source.lines() {
        let starts_item = matches!(line.as_bytes().first(), Some(b'#') | Some(b'p'))
            || line.starts_with("///");
        let previous_ended = out.last().is_some_and(|last: &&str| {
            *last == "}"
                || (last.ends_with(';') && !last.starts_with(' '))
                || (last.starts_with("//!") && !line.starts_with("//!"))
        });
        if starts_item && previous_ended {
            out.push("");
        }
        out.push(line);
    }
    out.join("\n") + "\n"
}

// ── data.rs ───────────────────────────────────────────────────────────────────

/// A type, as source rather than as tokens.
///
/// `quote!` puts a space between every token, which is right for a formatter to fix
/// and wrong for a file nothing formats. `schema.rs` goes through prettyplease;
/// `data.rs` is laid out here, comments and section rules included, and neither of
/// those survives a round trip through `syn`.
fn type_text(ty: &TokenStream) -> String {
    let mut out = String::new();
    let mut previous = ' ';
    for token in ty.to_string().chars() {
        if token == ' ' {
            continue;
        }
        if matches!(previous, ',' | ';') {
            out.push(' ');
        }
        out.push(token);
        previous = token;
    }
    out
}

fn method_name(field: &str) -> String {
    if KEYWORDS.contains(&field) {
        format!("r#{field}")
    } else {
        field.to_string()
    }
}

fn snake(camel: &str) -> String {
    let mut out = String::new();
    for (i, c) in camel.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The doc comment of an item, as `///` lines.
fn doc_of(attrs: &[Attribute], indent: &str) -> String {
    let mut out = String::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let Meta::NameValue(nv) = &attr.meta {
            if let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(s), .. }) = &nv.value {
                out.push_str(&format!("{indent}///{}\n", s.value()));
            }
        }
    }
    out
}

/// A TypeScript argument type, as the SDK spells it. The three the console has are
/// `string` and `number`; anything else is left as JSON so a command with a shape
/// nobody anticipated is still callable.
fn args_ty(ts: &str) -> &'static str {
    match ts {
        "string" => "String",
        "number" => "f64",
        "boolean" => "bool",
        _ => "serde_json::Value",
    }
}

fn render_data(
    source: &Source,
    entities: &[&'static EntityMeta],
    commands: &HashMap<&str, Vec<&'static CommandRegistration>>,
) -> Result<(String, BTreeSet<String>)> {
    let mut unknown = BTreeSet::new();
    let mut out = String::from(HEADER);
    out.push_str(
        "//! The show, reached by name instead of by string.\n\
         //!\n\
         //! `data::cues().nth(3).fade_in_ms().set(4000)` writes exactly what\n\
         //! `host::set(&[\"cues\", \"3\", \"fade_in_ms\"], &json!(4000))` writes — the wire is\n\
         //! the same generic path-plus-JSON it has always been, and this is the compiler\n\
         //! checking the spelling. Which is also the failure mode: a plugin built against a\n\
         //! newer schema than the station it is running on compiles fine and gets a\n\
         //! per-path error at the one call that names something the station has not got.\n\
         //!\n\
         //! Generated from the `EntityMeta` and `CommandRegistration` inventories.\n\
         //! Introspection is still the way to ask what *this* station has, including the\n\
         //! collections this build never heard of.\n\n",
    );
    out.push_str("use std::collections::HashMap;\n\nuse uuid::Uuid;\n\n");
    out.push_str("use crate::data::{Collection, Entity, Field, Singleton};\n");
    out.push_str("use crate::schema::*;\n\n");

    // ── Command arguments ────────────────────────────────────────────────────
    let mut all_commands: Vec<(&&'static EntityMeta, &'static CommandRegistration)> = Vec::new();
    for meta in entities {
        if let Some(cmds) = commands.get(meta.table_name.unwrap()) {
            for cmd in cmds {
                all_commands.push((meta, cmd));
            }
        }
    }
    if all_commands.iter().any(|(_, cmd)| !parse_args_schema(cmd.args_schema).is_empty()) {
        out.push_str(
            "// ── What a command is given ──────────────────────────────────────────────────\n\n",
        );
        for (meta, cmd) in &all_commands {
            let name = format!("{}{}Args", meta.entity_name, upper_first(cmd.command_name));
            let fields = parse_args_schema(cmd.args_schema);
            // A command that takes nothing is called with nothing; there is no empty
            // struct to make and none to name.
            if fields.is_empty() {
                continue;
            }
            out.push_str(&format!(
                "/// Arguments for `{}.{}`.\n",
                meta.table_name.unwrap(),
                cmd.command_name
            ));
            if fields.iter().all(|(_, _, optional)| *optional) {
                out.push_str(
                    "///\n/// Every field is optional, so `&Default::default()` is a whole call.\n",
                );
            }
            out.push_str("#[derive(Debug, Clone, Default, serde::Serialize)]\n");
            out.push_str("#[serde(rename_all = \"camelCase\")]\n");
            out.push_str(&format!("pub struct {name} {{\n"));
            for (field, ty, optional) in &fields {
                let rust = args_ty(ty);
                if *optional {
                    out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                    out.push_str(&format!("    pub {}: Option<{rust}>,\n", snake(field)));
                } else {
                    out.push_str(&format!("    pub {}: {rust},\n", snake(field)));
                }
            }
            out.push_str("}\n\n");
        }
    }

    // ── Entities ─────────────────────────────────────────────────────────────
    for meta in entities {
        let table = meta.table_name.unwrap();
        let name = meta.entity_name;
        let Some(Item::Struct(item)) = source.items.get(name) else {
            anyhow::bail!("{name} has a table but no struct in pult-schema's types/")
        };

        out.push_str(&format!(
            "// ── {table} {}\n\n",
            "─".repeat(74usize.saturating_sub(table.len() + 6))
        ));

        let doc = doc_of(&item.attrs, "");
        if meta.is_singleton {
            out.push_str(&doc);
            out.push_str(&format!("///\n/// The `{table}` singleton.\n"));
            out.push_str(&format!(
                "pub fn {table}() -> {name}Singleton {{\n    {name}Singleton {{ at: Singleton::at(\"{table}\") }}\n}}\n\n"
            ));
            out.push_str(&format!(
                "/// The `{table}` singleton, reached by [`{table}()`].\npub struct {name}Singleton {{\n    at: Singleton,\n}}\n\n"
            ));
            out.push_str(&format!("impl {name}Singleton {{\n"));
            out.push_str(
                "    /// The path this accessor writes, as the station spells it.\n    pub fn path(&self) -> &[String] {\n        self.at.path()\n    }\n\n",
            );
            out.push_str(&format!(
                "    /// The whole of it, or `None` where the show has not got one yet.\n    pub fn get(&self) -> Result<Option<{name}>, String> {{\n        self.at.get()\n    }}\n\n"
            ));
            out.push_str(&format!(
                "    /// Replace the whole of it.\n    pub fn set(&self, value: &{name}) -> Result<(), String> {{\n        self.at.set(value)\n    }}\n\n"
            ));
            out.push_str(
                "    /// Be told when it changes; updates arrive at `PultPlugin::on_update`.\n    pub fn subscribe(&self) -> u64 {\n        self.at.subscribe()\n    }\n",
            );
            out.push_str(&render_fields(source, item, meta, "        ", &mut unknown));
            out.push_str("}\n\n");
            continue;
        }

        // The collection.
        out.push_str(&doc);
        out.push_str(&format!("///\n/// The `{table}` collection.\n"));
        out.push_str(&format!(
            "pub fn {table}() -> {name}Collection {{\n    {name}Collection {{ at: Collection::at(\"{table}\") }}\n}}\n\n"
        ));
        out.push_str(&format!(
            "/// The `{table}` collection, reached by [`{table}()`].\npub struct {name}Collection {{\n    at: Collection,\n}}\n\n"
        ));
        out.push_str(&format!("impl {name}Collection {{\n"));
        out.push_str(
            "    /// The path this accessor writes, as the station spells it.\n    pub fn path(&self) -> &[String] {\n        self.at.path()\n    }\n\n",
        );
        out.push_str(&format!(
            "    /// Every row, in the show's own order.\n    pub fn get(&self) -> Result<Vec<{name}>, String> {{\n        self.at.get()\n    }}\n\n"
        ));
        out.push_str(&format!(
            "    /// One row by its id.\n    pub fn by_id(&self, id: Uuid) -> {name}Entity {{\n        {name}Entity {{ at: self.at.by_id(id) }}\n    }}\n\n"
        ));
        out.push_str(&format!(
            "    /// One row by position in the collection's order.\n    pub fn nth(&self, index: usize) -> {name}Entity {{\n        {name}Entity {{ at: self.at.nth(index) }}\n    }}\n\n"
        ));
        out.push_str(&format!(
            "    /// Add a row. One gesture, so it is one Ctrl-Z for whoever asked.\n    pub fn create(&self, value: &{name}) -> Result<(), String> {{\n        self.at.create(value)\n    }}\n\n"
        ));
        out.push_str(
            "    /// Be told when the collection itself changes — a create, a delete.\n    pub fn subscribe(&self) -> u64 {\n        self.at.subscribe()\n    }\n\n",
        );
        out.push_str(
            "    /// Be told about anything at or under the collection, a level moving\n    /// included.\n    pub fn subscribe_deep(&self) -> u64 {\n        self.at.subscribe_deep()\n    }\n\n",
        );
        out.push_str(COLLECTION_VERBS);
        out.push_str("}\n\n");

        // The row.
        out.push_str(&format!(
            "/// One `{table}` row, reached by [`{name}Collection::by_id`] or\n/// [`{name}Collection::nth`].\npub struct {name}Entity {{\n    at: Entity,\n}}\n\n"
        ));
        out.push_str(&format!("impl {name}Entity {{\n"));
        out.push_str(
            "    /// The path this accessor writes, as the station spells it.\n    pub fn path(&self) -> &[String] {\n        self.at.path()\n    }\n\n",
        );
        out.push_str(&format!(
            "    /// The whole row.\n    pub fn get(&self) -> Result<{name}, String> {{\n        self.at.get()\n    }}\n\n"
        ));
        out.push_str(&format!(
            "    /// Replace the whole row.\n    pub fn set(&self, value: &{name}) -> Result<(), String> {{\n        self.at.set(value)\n    }}\n\n"
        ));
        out.push_str(
            "    /// Delete the row.\n    pub fn delete(&self) -> Result<(), String> {\n        self.at.delete()\n    }\n\n",
        );
        out.push_str(
            "    /// Be told when this row changes.\n    pub fn subscribe(&self) -> u64 {\n        self.at.subscribe_deep()\n    }\n",
        );
        out.push_str(&render_fields(source, item, meta, "        ", &mut unknown));

        if let Some(cmds) = commands.get(table) {
            for cmd in cmds {
                let args_name = format!("{name}{}Args", upper_first(cmd.command_name));
                out.push('\n');
                out.push_str(&doc_of_text(cmd.doc, "    "));
                if !cmd.doc.is_empty() {
                    out.push_str("    ///\n");
                }
                out.push_str(&format!(
                    "    /// The command `{table}.{}`, which the station applies to the row and\n    /// replicates like any other write.\n",
                    cmd.command_name
                ));
                if parse_args_schema(cmd.args_schema).is_empty() {
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Result<(), String> {{\n        self.at.command(\"{}\", &serde_json::json!({{}}))\n    }}\n",
                        snake(cmd.command_name),
                        cmd.command_name
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {}(&self, args: &{args_name}) -> Result<(), String> {{\n        self.at.command(\"{}\", args)\n    }}\n",
                        snake(cmd.command_name),
                        cmd.command_name
                    ));
                }
            }
        }
        out.push_str("}\n\n");
    }

    Ok((out, unknown))
}

/// The verbs the runtime answers on every collection.
///
/// Written for all of them rather than for the three that do anything, because this
/// file is generated from the registry and must not know a table by name — the same
/// reason `frontend/src/lib/ws/data.ts` puts them everywhere. The station refuses each
/// elsewhere, naming the path.
const COLLECTION_VERBS: &str = r#"    /// Put something back where it rests when nothing is driving it.
    ///
    /// `programmer_values`. `{ "fixtureId": <uuid> }` sends every output parameter of
    /// that fixture home, and naming a `parameterKind` as well sends just the one. The
    /// station resolves it against what it holds, so a plugin can ask for home without
    /// being able to read the rig.
    pub fn home(&self, args: &serde_json::Value) -> Result<(), String> {
        self.at.verb("__home", args)
    }

    /// Make where a parameter rests be wherever it is now.
    ///
    /// `fixtures`, and the same arguments as [`Self::home`] backwards. Evaluated at
    /// the instant it is asked, which is why it is a verb and not a write.
    pub fn take_home(&self, args: &serde_json::Value) -> Result<(), String> {
        self.at.verb("__set_home", args)
    }

    /// Save: a point to come back to.
    ///
    /// `versions`. `{ "name": "Act 1" }`, and a quick Save gives no name. A verb
    /// rather than a create because two of the row's fields are the engine's own.
    pub fn checkpoint(&self, args: &serde_json::Value) -> Result<(), String> {
        self.at.verb("__checkpoint", args)
    }
"#;

/// Every field of an entity, as an accessor.
fn render_fields(
    source: &Source,
    item: &syn::ItemStruct,
    meta: &EntityMeta,
    _indent: &str,
    unknown: &mut BTreeSet<String>,
) -> String {
    let mut out = String::new();
    for field in &item.fields {
        let Some(ident) = field.ident.as_ref() else { continue };
        let name = ident.to_string();
        let ty = rewrite(&field.ty, source, unknown);
        let lifecycle = meta.field_lifecycle(&name);
        out.push('\n');
        out.push_str(&doc_of(&field.attrs, "    "));
        if let Some(lifecycle) = lifecycle {
            if !doc_of(&field.attrs, "    ").is_empty() {
                out.push_str("    ///\n");
            }
            out.push_str(&format!(
                "    /// {}.\n",
                format!("{lifecycle:?}").to_uppercase()
            ));
        }
        out.push_str(&format!(
            "    pub fn {}(&self) -> Field<{}> {{\n        self.at.field(\"{name}\")\n    }}\n",
            method_name(&name),
            type_text(&ty),
        ));
    }
    out
}

fn doc_of_text(doc: &str, indent: &str) -> String {
    let mut out = String::new();
    for line in doc.lines() {
        let space = if line.starts_with(' ') || line.is_empty() { "" } else { " " };
        out.push_str(&format!("{indent}///{space}{line}\n"));
    }
    out
}

fn upper_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// `[{"name":"cueId","type":"string","optional":false}]` → the fields of an args struct.
fn parse_args_schema(schema: &str) -> Vec<(String, String, bool)> {
    let Ok(serde_json::Value::Array(entries)) = serde_json::from_str::<serde_json::Value>(schema)
    else {
        return Vec::new();
    };
    entries
        .iter()
        .filter_map(|entry| {
            Some((
                entry.get("name")?.as_str()?.to_string(),
                entry.get("type")?.as_str()?.to_string(),
                entry.get("optional").and_then(|v| v.as_bool()).unwrap_or(false),
            ))
        })
        .collect()
}

// ── The whole of it ───────────────────────────────────────────────────────────

/// What the SDK's generated half is, as file contents. Pure, so a test can compare it
/// against what is checked in and say "somebody added a field and did not regenerate".
pub fn render(workspace: &Path) -> Result<Vec<(PathBuf, String)>> {
    let source = Source::read(&[
        workspace.join("crates/pult-schema/src/types"),
        workspace.join("crates/pult-schema/src/events"),
    ])?;

    let entities = EntityMeta::all_with_tables();
    let roots: Vec<&str> = entities.iter().map(|m| m.entity_name).collect();
    let wanted = reachable(&source, &roots);

    let mut commands: HashMap<&str, Vec<&'static CommandRegistration>> = HashMap::new();
    for cmd in inventory::iter::<CommandRegistration>() {
        commands.entry((cmd.entity_table)()).or_default().push(cmd);
    }
    for cmds in commands.values_mut() {
        cmds.sort_by_key(|c| c.command_name);
    }

    let (schema, mut unknown) = render_schema(&source, &wanted)?;
    let (data, unknown_data) = render_data(&source, &entities, &commands)?;
    unknown.extend(unknown_data);

    if !unknown.is_empty() {
        let names: Vec<&str> = unknown.iter().map(String::as_str).collect();
        eprintln!(
            "  note: {} untyped as `serde_json::Value` in the SDK mirror — {}",
            names.len(),
            names.join(", ")
        );
    }

    let dir = workspace.join("plugins/sdk/src/generated");
    Ok(vec![
        (
            dir.join("mod.rs"),
            format!(
                "{HEADER}//! The typed half of the SDK. See `pult-codegen`'s `sdk.rs` for what it is\n\
                 //! and why the wire underneath it stays generic.\n\n\
                 pub mod data;\npub mod schema;\n"
            ),
        ),
        (dir.join("schema.rs"), schema),
        (dir.join("data.rs"), data),
    ])
}

pub fn generate(workspace: &Path) -> Result<()> {
    let files = render(workspace)?;
    let dir = workspace.join("plugins/sdk/src/generated");
    fs::create_dir_all(&dir)?;
    for (path, content) in &files {
        fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    }
    eprintln!("✓ Generated the plugin SDK's typed half → {}", dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..").canonicalize().unwrap()
    }

    /// What is checked in is what this run would write.
    ///
    /// The generated SDK is committed rather than built into `OUT_DIR`, so the plugins
    /// workspace stays buildable without the console's — which is worth exactly as
    /// much as the guarantee that the two are the same. A field added to the schema
    /// and not regenerated fails here rather than at the plugin author's desk.
    #[test]
    fn checked_in_sdk_is_current() {
        let workspace = workspace();
        for (path, expected) in render(&workspace).expect("the SDK renders") {
            let found = fs::read_to_string(&path).unwrap_or_default();
            assert_eq!(
                found,
                expected,
                "{} is out of date — run `cargo run -p pult-codegen -- generate`",
                path.display()
            );
        }
    }
}
