// Allow generated code that references ::pult_schema::... to work within this crate.
extern crate self as pult_schema;

pub mod lifecycle;
pub mod path;
pub mod handle;
pub mod traits;
pub mod events;
pub mod types;
pub mod stock;
pub mod ws;
pub mod sql;
pub mod db;
pub mod registry;
pub mod commands;

pub use pult_macros::PultSchema;
pub use pult_macros::pult_commands;

pub mod prelude {
    pub use crate::lifecycle::Lifecycle;
    pub use crate::path::{Path, PathPattern, PathSegment};
    pub use crate::handle::{DataHandle, EntityCollectionAccessor, FieldAccessor, HandleError, ShowDataRoot};
    pub use crate::traits::PultEntity;
    pub use crate::sql::{ColumnGetter, PultSqlRow, SqlLiteral};
    pub use crate::PultSchema;
}

// Collection and singleton accessors on ShowDataRoot (`data.sequences()`, `data.show()`)
// are generated by #[derive(PultSchema)] from each entity's table name. There is no
// list of them to maintain here.
