use std::pin::Pin;
use std::future::Future;

use sqlx::SqlitePool;

use crate::{lifecycle::Lifecycle, path::{Path, PathSegment}};

// ── Fn pointer types ──────────────────────────────────────────────────────────

/// Save all entities of one type from a serialized ShowState snapshot to SQLite.
/// The snapshot is `serde_json::to_value(&ShowState)`. The fn is generated by
/// #[derive(PultSchema)] and knows which key to look up in the snapshot.
pub type SaveAllFn = fn(SqlitePool, serde_json::Value) -> Pin<Box<dyn Future<Output = anyhow::Result<()>> + Send>>;

/// Load all entities of one type from SQLite, returning a serde_json::Value in
/// the shape that ShowState's Deserialize impl expects:
///   - collection entities → JSON Object keyed by UUID string
///   - singleton entities  → JSON null | entity object
pub type LoadAllFn = fn(SqlitePool) -> Pin<Box<dyn Future<Output = anyhow::Result<serde_json::Value>> + Send>>;

/// Round-trip one entity through its concrete Rust type.
/// Rejects values that are not valid for the type and fills in serde defaults,
/// so the engine can hold entities as JSON without losing type checking.
pub type ValidateFn = fn(serde_json::Value) -> anyhow::Result<serde_json::Value>;

/// Write one entity to SQLite.
pub type UpsertOneFn = fn(SqlitePool, serde_json::Value) -> Pin<Box<dyn Future<Output = anyhow::Result<()>> + Send>>;

/// Delete one entity from SQLite by primary key.
pub type DeleteOneFn = fn(SqlitePool, uuid::Uuid) -> Pin<Box<dyn Future<Output = anyhow::Result<()>> + Send>>;

// ── EntityMeta ────────────────────────────────────────────────────────────────

/// Metadata about a PultSchema entity, auto-submitted to inventory by #[derive(PultSchema)].
pub struct EntityMeta {
    pub entity_name: &'static str,
    pub table_name: Option<&'static str>,
    /// True for singleton entities (e.g. Show); false for collection entities (e.g. Sequence).
    pub is_singleton: bool,
    /// Returns Some(create_table_sql) for PERSISTED entities, None otherwise.
    pub create_table_sql: fn() -> Option<String>,
    /// Comma-separated column definitions, or None for entities without a table.
    /// Used to bring an existing showfile's tables up to the current schema.
    pub column_defs: fn() -> Option<&'static str>,
    pub field_lifecycles: fn() -> &'static [(&'static str, Lifecycle)],
    /// Save all entities from a ShowState snapshot to SQLite. None for entities
    /// without a table.
    pub save_all: Option<SaveAllFn>,
    /// Load all entities from SQLite into the JSON shape ShowState::Deserialize expects.
    /// None for entities without a table.
    pub load_all: Option<LoadAllFn>,
    /// The primary key field name, if the entity has one.
    pub primary_key: Option<&'static str>,
    /// Validate and normalise one entity value against its Rust type.
    pub validate: ValidateFn,
    /// Write one entity to SQLite. None for entities without a table.
    pub upsert_one: Option<UpsertOneFn>,
    /// Delete one entity from SQLite. None for entities without a table.
    pub delete_one: Option<DeleteOneFn>,
}

impl EntityMeta {
    /// The registered entity whose table matches `table`.
    pub fn by_table(table: &str) -> Option<&'static EntityMeta> {
        inventory::iter::<EntityMeta>().find(|m| m.table_name == Some(table))
    }

    /// Every registered entity that has a table, in a stable order.
    pub fn all_with_tables() -> Vec<&'static EntityMeta> {
        let mut all: Vec<&'static EntityMeta> =
            inventory::iter::<EntityMeta>().filter(|m| m.table_name.is_some()).collect();
        all.sort_by_key(|m| m.entity_name);
        all
    }

    /// The lifecycle of one of this entity's fields, or None if the name is not a field
    /// (a registered command, for instance).
    pub fn field_lifecycle(&self, field: &str) -> Option<Lifecycle> {
        (self.field_lifecycles)().iter().find(|(n, _)| *n == field).map(|(_, lc)| *lc)
    }
}

inventory::collect!(EntityMeta);

// ── path_lifecycle ────────────────────────────────────────────────────────────

/// Derive the lifecycle of an operation from its path alone.
///
/// Both the WS handler (sender) and sync peer (receiver) call this so the lifecycle
/// never needs to be transmitted over the wire — the schema is the source of truth.
///
/// Rules:
/// - `[collection, "__create"]`              → Persisted
/// - `[collection, id, "__delete"]`          → Persisted
/// - `[collection, id, field]`               → look up field in EntityMeta registry
///   - known SYNCED/LOCAL/PERSISTED field    → that lifecycle
///   - unknown name (a registered command)   → Synced
/// - anything else                           → Persisted
pub fn path_lifecycle(path: &Path) -> Lifecycle {
    match path.as_slice() {
        [PathSegment::Key(_), PathSegment::Key(a)] if a == "__create" => Lifecycle::Persisted,
        [PathSegment::Key(_), PathSegment::Id(_), PathSegment::Key(a)] if a == "__delete" => {
            Lifecycle::Persisted
        }
        [PathSegment::Key(table), PathSegment::Id(_), PathSegment::Key(field)] => {
            match EntityMeta::by_table(table) {
                // Name not found among the fields → it is a registered command → Synced
                Some(meta) => meta.field_lifecycle(field).unwrap_or(Lifecycle::Synced),
                None => Lifecycle::Persisted,
            }
        }
        _ => Lifecycle::Persisted,
    }
}
