use std::pin::Pin;
use std::future::Future;

use sqlx::SqlitePool;

use crate::{lifecycle::Lifecycle, path::{Path, PathSegment}};

// ── Fn pointer types ──────────────────────────────────────────────────────────

/// Save all entities of one type from a serialized ShowState snapshot to SQLite.
/// The snapshot is `serde_json::to_value(&ShowState)`. The fn is generated by
/// #[derive(PultSchema)] and knows which key to look up in the snapshot.
pub type SaveAllFn = fn(SqlitePool, serde_json::Value) -> Pin<Box<dyn Future<Output = anyhow::Result<()>> + Send>>;

/// Load all entities of one type from SQLite, returning a serde_json::Value in
/// the shape that ShowState's Deserialize impl expects:
///   - collection entities → JSON Object keyed by UUID string
///   - singleton entities  → JSON null | entity object
pub type LoadAllFn = fn(SqlitePool) -> Pin<Box<dyn Future<Output = anyhow::Result<serde_json::Value>> + Send>>;

// ── EntityMeta ────────────────────────────────────────────────────────────────

/// Metadata about a PultSchema entity, auto-submitted to inventory by #[derive(PultSchema)].
pub struct EntityMeta {
    pub entity_name: &'static str,
    pub table_name: Option<&'static str>,
    /// Returns Some(create_table_sql) for PERSISTED entities, None otherwise.
    pub create_table_sql: fn() -> Option<String>,
    pub field_lifecycles: fn() -> &'static [(&'static str, Lifecycle)],
    /// Save all entities from a ShowState snapshot to SQLite. None for entities
    /// without a table.
    pub save_all: Option<SaveAllFn>,
    /// Load all entities from SQLite into the JSON shape ShowState::Deserialize expects.
    /// None for entities without a table.
    pub load_all: Option<LoadAllFn>,
}

inventory::collect!(EntityMeta);

// ── path_lifecycle ────────────────────────────────────────────────────────────

/// Derive the lifecycle of an operation from its path alone.
///
/// Both the WS handler (sender) and sync peer (receiver) call this so the lifecycle
/// never needs to be transmitted over the wire — the schema is the source of truth.
///
/// Rules:
/// - `[collection, "__create"]`              → Persisted
/// - `[collection, id, "__delete"]`          → Persisted
/// - `[collection, id, field]`               → look up field in EntityMeta registry
///   - known SYNCED/LOCAL/PERSISTED field    → that lifecycle
///   - unknown name (a registered command)   → Synced
/// - anything else                           → Persisted
pub fn path_lifecycle(path: &Path) -> Lifecycle {
    match path.as_slice() {
        [PathSegment::Key(_), PathSegment::Key(a)] if a == "__create" => Lifecycle::Persisted,
        [PathSegment::Key(_), PathSegment::Id(_), PathSegment::Key(a)] if a == "__delete" => {
            Lifecycle::Persisted
        }
        [PathSegment::Key(table), PathSegment::Id(_), PathSegment::Key(field)] => {
            for meta in inventory::iter::<EntityMeta>() {
                if meta.table_name == Some(table.as_str()) {
                    for (fname, lc) in (meta.field_lifecycles)() {
                        if *fname == field.as_str() {
                            return *lc;
                        }
                    }
                    // Name not found among fields → it's a registered command → Synced
                    return Lifecycle::Synced;
                }
            }
            Lifecycle::Persisted
        }
        _ => Lifecycle::Persisted,
    }
}
