-- Auto-generated by pult-codegen — do not edit manually.
-- Run: cargo run -p pult-codegen -- generate

CREATE TABLE IF NOT EXISTS cues (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    number REAL NOT NULL,
    captures TEXT NOT NULL,
    follow_mode TEXT NOT NULL,
    fade_in_ms INTEGER NOT NULL,
    fade_out_ms INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS fixtures (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    fixture_type_id TEXT NOT NULL,
    universe INTEGER NOT NULL,
    dmx_address INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS fixture_types (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    channel_count INTEGER NOT NULL,
    parameters TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sequences (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    cue_ids TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS show (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS oplog (
    seq         INTEGER NOT NULL,
    node_id     TEXT NOT NULL,
    op_id       TEXT NOT NULL,
    clock_json  TEXT NOT NULL,
    path_json   TEXT NOT NULL,
    value_json  TEXT NOT NULL,
    lifecycle   TEXT NOT NULL,
    timestamp   TEXT NOT NULL,
    PRIMARY KEY (node_id, seq)
);