-- Auto-generated by pult-codegen — do not edit manually.
-- Run: cargo run -p pult-codegen -- generate

CREATE TABLE IF NOT EXISTS cues (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    number REAL NOT NULL,
    captures TEXT NOT NULL,
    follow_mode TEXT NOT NULL,
    fade_in_ms INTEGER NOT NULL,
    fade_out_ms INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS fixtures (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    fixture_type_id TEXT NOT NULL,
    address TEXT NOT NULL,
    position TEXT,
    home_values TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fixture_types (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    channel_count INTEGER NOT NULL,
    parameters TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS flows (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    enabled INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS flow_edges (
    id TEXT NOT NULL PRIMARY KEY,
    flow_id TEXT NOT NULL,
    from_node TEXT NOT NULL,
    from_port INTEGER NOT NULL,
    to_node TEXT NOT NULL,
    to_port INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS flow_nodes (
    id TEXT NOT NULL PRIMARY KEY,
    flow_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS groups (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    query TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS layouts (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    tree TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outputs (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    target TEXT,
    universes TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    node_id TEXT
);

CREATE TABLE IF NOT EXISTS plugin_data (
    id TEXT NOT NULL PRIMARY KEY,
    plugin_id TEXT NOT NULL,
    store TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS plugin_packages (
    id TEXT NOT NULL PRIMARY KEY,
    plugin_id TEXT NOT NULL,
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    api TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    stage TEXT NOT NULL,
    config TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sequences (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    cue_ids TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS show (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    history_depth INTEGER NOT NULL,
    home_fade_ms INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS speed_masters (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    bpm REAL NOT NULL,
    multiplier REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS stage_plans (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    asset TEXT NOT NULL,
    width_px INTEGER NOT NULL,
    height_px INTEGER NOT NULL,
    origin TEXT NOT NULL,
    metres_per_pixel REAL NOT NULL,
    rotation_deg REAL NOT NULL,
    opacity REAL NOT NULL,
    visible INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    colour TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS collection_order (
    table_name TEXT NOT NULL,
    entity_id  TEXT NOT NULL,
    position   INTEGER NOT NULL,
    PRIMARY KEY (table_name, entity_id)
);

CREATE TABLE IF NOT EXISTS oplog (
    seq         INTEGER NOT NULL,
    node_id     TEXT NOT NULL,
    op_id       TEXT NOT NULL,
    clock_json  TEXT NOT NULL,
    path_json   TEXT NOT NULL,
    value_json  TEXT NOT NULL,
    lifecycle   TEXT NOT NULL,
    timestamp   TEXT NOT NULL,
    user_id     TEXT,
    previous_json TEXT,
    undoes      TEXT,
    gesture     TEXT,
    PRIMARY KEY (node_id, seq)
);

CREATE INDEX IF NOT EXISTS oplog_by_people
    ON oplog (user_id, timestamp DESC, seq DESC);

CREATE TABLE IF NOT EXISTS oplog_floor (
    node_id           TEXT NOT NULL PRIMARY KEY,
    pruned_through_seq INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS assets (
    sha256     TEXT NOT NULL PRIMARY KEY,
    mime       TEXT NOT NULL,
    byte_len   INTEGER NOT NULL,
    bytes      BLOB NOT NULL,
    created_at TEXT NOT NULL
);