// Auto-generated by pult-codegen — do not edit manually.
// Run: cargo run -p pult-codegen -- generate

import type { PathProxy, SubscribeOptions } from './proxy.js';
import type { PultWsClient } from './client.js';
import { createDataProxy } from './proxy.js';
import type { Cue } from '../generated/Cue.js';
import type { Fixture } from '../generated/Fixture.js';
import type { FixtureType } from '../generated/FixtureType.js';
import type { Flow } from '../generated/Flow.js';
import type { FlowEdge } from '../generated/FlowEdge.js';
import type { FlowNode } from '../generated/FlowNode.js';
import type { Group } from '../generated/Group.js';
import type { Layer } from '../generated/Layer.js';
import type { Layout } from '../generated/Layout.js';
import type { NamedAsset } from '../generated/NamedAsset.js';
import type { OutputConfig } from '../generated/OutputConfig.js';
import type { PluginDatum } from '../generated/PluginDatum.js';
import type { PluginPackage } from '../generated/PluginPackage.js';
import type { ProgrammerValue } from '../generated/ProgrammerValue.js';
import type { SceneClass } from '../generated/SceneClass.js';
import type { SceneObject } from '../generated/SceneObject.js';
import type { Sequence } from '../generated/Sequence.js';
import type { Show } from '../generated/Show.js';
import type { SpeedMaster } from '../generated/SpeedMaster.js';
import type { StagePlan } from '../generated/StagePlan.js';
import type { Station } from '../generated/Station.js';
import type { Symbol } from '../generated/Symbol.js';
import type { User } from '../generated/User.js';
import type { Version } from '../generated/Version.js';

// ── Entity handles ───────────────────────────────────────────────────────────

export type CueEntity = PathProxy<Cue> & {
  delete(): Promise<void>;
};

export type FixtureEntity = PathProxy<Fixture> & {
  delete(): Promise<void>;
};

export type FixtureTypeEntity = PathProxy<FixtureType> & {
  delete(): Promise<void>;
};

export type FlowEntity = PathProxy<Flow> & {
  delete(): Promise<void>;
};

export type FlowEdgeEntity = PathProxy<FlowEdge> & {
  delete(): Promise<void>;
};

export type FlowNodeEntity = PathProxy<FlowNode> & {
  delete(): Promise<void>;
  press(): Promise<void>;
};

export type GroupEntity = PathProxy<Group> & {
  delete(): Promise<void>;
};

export type LayerEntity = PathProxy<Layer> & {
  delete(): Promise<void>;
};

export type LayoutEntity = PathProxy<Layout> & {
  delete(): Promise<void>;
};

export type NamedAssetEntity = PathProxy<NamedAsset> & {
  delete(): Promise<void>;
};

export type OutputConfigEntity = PathProxy<OutputConfig> & {
  delete(): Promise<void>;
};

export type PluginDatumEntity = PathProxy<PluginDatum> & {
  delete(): Promise<void>;
};

export type PluginPackageEntity = PathProxy<PluginPackage> & {
  delete(): Promise<void>;
};

export type ProgrammerValueEntity = PathProxy<ProgrammerValue> & {
  delete(): Promise<void>;
};

export type SceneClassEntity = PathProxy<SceneClass> & {
  delete(): Promise<void>;
};

export type SceneObjectEntity = PathProxy<SceneObject> & {
  delete(): Promise<void>;
};

export type SequenceEntity = PathProxy<Sequence> & {
  delete(): Promise<void>;
  goNext(args: { at?: number }): Promise<void>;
  goToCue(args: { cueId: string, at?: number }): Promise<void>;
  off(args: { at?: number }): Promise<void>;
};

export type SpeedMasterEntity = PathProxy<SpeedMaster> & {
  delete(): Promise<void>;
};

export type StagePlanEntity = PathProxy<StagePlan> & {
  delete(): Promise<void>;
};

export type StationEntity = PathProxy<Station> & {
  delete(): Promise<void>;
};

export type SymbolEntity = PathProxy<Symbol> & {
  delete(): Promise<void>;
};

export type UserEntity = PathProxy<User> & {
  delete(): Promise<void>;
};

export type VersionEntity = PathProxy<Version> & {
  delete(): Promise<void>;
};

// ── Collection handles ──────────────────────────────────────────────────────

export type CueCollection = {
  get(): Promise<Cue[]>;
  set(value: Cue[]): Promise<void>;
  subscribe(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): CueEntity;
  nth(n: number): CueEntity;
  create(entity: Cue): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: CueEntity;
};

export type FixtureCollection = {
  get(): Promise<Fixture[]>;
  set(value: Fixture[]): Promise<void>;
  subscribe(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureEntity;
  nth(n: number): FixtureEntity;
  create(entity: Fixture): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: FixtureEntity;
};

export type FixtureTypeCollection = {
  get(): Promise<FixtureType[]>;
  set(value: FixtureType[]): Promise<void>;
  subscribe(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureTypeEntity;
  nth(n: number): FixtureTypeEntity;
  create(entity: FixtureType): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: FixtureTypeEntity;
};

export type FlowCollection = {
  get(): Promise<Flow[]>;
  set(value: Flow[]): Promise<void>;
  subscribe(cb: (value: Flow[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Flow[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowEntity;
  nth(n: number): FlowEntity;
  create(entity: Flow): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: FlowEntity;
};

export type FlowEdgeCollection = {
  get(): Promise<FlowEdge[]>;
  set(value: FlowEdge[]): Promise<void>;
  subscribe(cb: (value: FlowEdge[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FlowEdge[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowEdgeEntity;
  nth(n: number): FlowEdgeEntity;
  create(entity: FlowEdge): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: FlowEdgeEntity;
};

export type FlowNodeCollection = {
  get(): Promise<FlowNode[]>;
  set(value: FlowNode[]): Promise<void>;
  subscribe(cb: (value: FlowNode[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FlowNode[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowNodeEntity;
  nth(n: number): FlowNodeEntity;
  create(entity: FlowNode): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: FlowNodeEntity;
};

export type GroupCollection = {
  get(): Promise<Group[]>;
  set(value: Group[]): Promise<void>;
  subscribe(cb: (value: Group[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Group[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): GroupEntity;
  nth(n: number): GroupEntity;
  create(entity: Group): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: GroupEntity;
};

export type LayerCollection = {
  get(): Promise<Layer[]>;
  set(value: Layer[]): Promise<void>;
  subscribe(cb: (value: Layer[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Layer[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): LayerEntity;
  nth(n: number): LayerEntity;
  create(entity: Layer): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: LayerEntity;
};

export type LayoutCollection = {
  get(): Promise<Layout[]>;
  set(value: Layout[]): Promise<void>;
  subscribe(cb: (value: Layout[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Layout[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): LayoutEntity;
  nth(n: number): LayoutEntity;
  create(entity: Layout): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: LayoutEntity;
};

export type NamedAssetCollection = {
  get(): Promise<NamedAsset[]>;
  set(value: NamedAsset[]): Promise<void>;
  subscribe(cb: (value: NamedAsset[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: NamedAsset[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): NamedAssetEntity;
  nth(n: number): NamedAssetEntity;
  create(entity: NamedAsset): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: NamedAssetEntity;
};

export type OutputConfigCollection = {
  get(): Promise<OutputConfig[]>;
  set(value: OutputConfig[]): Promise<void>;
  subscribe(cb: (value: OutputConfig[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: OutputConfig[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): OutputConfigEntity;
  nth(n: number): OutputConfigEntity;
  create(entity: OutputConfig): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: OutputConfigEntity;
};

export type PluginDatumCollection = {
  get(): Promise<PluginDatum[]>;
  set(value: PluginDatum[]): Promise<void>;
  subscribe(cb: (value: PluginDatum[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: PluginDatum[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): PluginDatumEntity;
  nth(n: number): PluginDatumEntity;
  create(entity: PluginDatum): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: PluginDatumEntity;
};

export type PluginPackageCollection = {
  get(): Promise<PluginPackage[]>;
  set(value: PluginPackage[]): Promise<void>;
  subscribe(cb: (value: PluginPackage[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: PluginPackage[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): PluginPackageEntity;
  nth(n: number): PluginPackageEntity;
  create(entity: PluginPackage): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: PluginPackageEntity;
};

export type ProgrammerValueCollection = {
  get(): Promise<ProgrammerValue[]>;
  set(value: ProgrammerValue[]): Promise<void>;
  subscribe(cb: (value: ProgrammerValue[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: ProgrammerValue[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): ProgrammerValueEntity;
  nth(n: number): ProgrammerValueEntity;
  create(entity: ProgrammerValue): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: ProgrammerValueEntity;
};

export type SceneClassCollection = {
  get(): Promise<SceneClass[]>;
  set(value: SceneClass[]): Promise<void>;
  subscribe(cb: (value: SceneClass[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: SceneClass[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SceneClassEntity;
  nth(n: number): SceneClassEntity;
  create(entity: SceneClass): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: SceneClassEntity;
};

export type SceneObjectCollection = {
  get(): Promise<SceneObject[]>;
  set(value: SceneObject[]): Promise<void>;
  subscribe(cb: (value: SceneObject[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: SceneObject[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SceneObjectEntity;
  nth(n: number): SceneObjectEntity;
  create(entity: SceneObject): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: SceneObjectEntity;
};

export type SequenceCollection = {
  get(): Promise<Sequence[]>;
  set(value: Sequence[]): Promise<void>;
  subscribe(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SequenceEntity;
  nth(n: number): SequenceEntity;
  create(entity: Sequence): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: SequenceEntity;
};

export type SpeedMasterCollection = {
  get(): Promise<SpeedMaster[]>;
  set(value: SpeedMaster[]): Promise<void>;
  subscribe(cb: (value: SpeedMaster[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: SpeedMaster[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SpeedMasterEntity;
  nth(n: number): SpeedMasterEntity;
  create(entity: SpeedMaster): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: SpeedMasterEntity;
};

export type StagePlanCollection = {
  get(): Promise<StagePlan[]>;
  set(value: StagePlan[]): Promise<void>;
  subscribe(cb: (value: StagePlan[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: StagePlan[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): StagePlanEntity;
  nth(n: number): StagePlanEntity;
  create(entity: StagePlan): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: StagePlanEntity;
};

export type StationCollection = {
  get(): Promise<Station[]>;
  set(value: Station[]): Promise<void>;
  subscribe(cb: (value: Station[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Station[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): StationEntity;
  nth(n: number): StationEntity;
  create(entity: Station): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: StationEntity;
};

export type SymbolCollection = {
  get(): Promise<Symbol[]>;
  set(value: Symbol[]): Promise<void>;
  subscribe(cb: (value: Symbol[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Symbol[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SymbolEntity;
  nth(n: number): SymbolEntity;
  create(entity: Symbol): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: SymbolEntity;
};

export type UserCollection = {
  get(): Promise<User[]>;
  set(value: User[]): Promise<void>;
  subscribe(cb: (value: User[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: User[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): UserEntity;
  nth(n: number): UserEntity;
  create(entity: User): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: UserEntity;
};

export type VersionCollection = {
  get(): Promise<Version[]>;
  set(value: Version[]): Promise<void>;
  subscribe(cb: (value: Version[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Version[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): VersionEntity;
  nth(n: number): VersionEntity;
  create(entity: Version): Promise<void>;
  home(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  takeHome(args: { fixtureId: string; parameterKind?: unknown }): Promise<void>;
  checkpoint(args: { name?: string; automatic?: boolean }): Promise<void>;
  [n: number]: VersionEntity;
};

// ── DataRoot ─────────────────────────────────────────────────────────────────

/** Typed root for the pult:data context. Every field maps to a live path proxy. */
export type DataRoot = {
  cues: CueCollection;
  fixtures: FixtureCollection;
  fixture_types: FixtureTypeCollection;
  flows: FlowCollection;
  flow_edges: FlowEdgeCollection;
  flow_nodes: FlowNodeCollection;
  groups: GroupCollection;
  layers: LayerCollection;
  layouts: LayoutCollection;
  named_assets: NamedAssetCollection;
  outputs: OutputConfigCollection;
  plugin_data: PluginDatumCollection;
  plugin_packages: PluginPackageCollection;
  programmer_values: ProgrammerValueCollection;
  classes: SceneClassCollection;
  scene_objects: SceneObjectCollection;
  sequences: SequenceCollection;
  show: PathProxy<Show | null>;
  speed_masters: SpeedMasterCollection;
  stage_plans: StagePlanCollection;
  stations: StationCollection;
  symbols: SymbolCollection;
  users: UserCollection;
  versions: VersionCollection;
};

/** Create the typed root proxy. The runtime proxy handles all DataRoot operations generically. */
export function createRootProxy(client: PultWsClient): DataRoot {
  return createDataProxy(client) as unknown as DataRoot;
}
