// Auto-generated by pult-codegen — do not edit manually.
// Run: cargo run -p pult-codegen -- generate

import type { PathProxy, SubscribeOptions } from './proxy.js';
import type { PultWsClient } from './client.js';
import { createDataProxy } from './proxy.js';
import type { Cue } from '../generated/Cue.js';
import type { Fixture } from '../generated/Fixture.js';
import type { FixtureType } from '../generated/FixtureType.js';
import type { Sequence } from '../generated/Sequence.js';
import type { Show } from '../generated/Show.js';

// ── Entity handles ───────────────────────────────────────────────────────────

export type CueEntity = PathProxy<Cue> & {
  delete(): Promise<void>;
};

export type FixtureEntity = PathProxy<Fixture> & {
  delete(): Promise<void>;
};

export type FixtureTypeEntity = PathProxy<FixtureType> & {
  delete(): Promise<void>;
};

export type SequenceEntity = PathProxy<Sequence> & {
  delete(): Promise<void>;
  goNext(): Promise<void>;
  goToCue(args: { cueId: string }): Promise<void>;
};

// ── Collection handles ──────────────────────────────────────────────────────

export type CueCollection = {
  get(): Promise<Cue[]>;
  set(value: Cue[]): Promise<void>;
  subscribe(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): CueEntity;
  nth(n: number): CueEntity;
  create(entity: Cue): Promise<void>;
  [n: number]: CueEntity;
};

export type FixtureCollection = {
  get(): Promise<Fixture[]>;
  set(value: Fixture[]): Promise<void>;
  subscribe(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureEntity;
  nth(n: number): FixtureEntity;
  create(entity: Fixture): Promise<void>;
  [n: number]: FixtureEntity;
};

export type FixtureTypeCollection = {
  get(): Promise<FixtureType[]>;
  set(value: FixtureType[]): Promise<void>;
  subscribe(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureTypeEntity;
  nth(n: number): FixtureTypeEntity;
  create(entity: FixtureType): Promise<void>;
  [n: number]: FixtureTypeEntity;
};

export type SequenceCollection = {
  get(): Promise<Sequence[]>;
  set(value: Sequence[]): Promise<void>;
  subscribe(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SequenceEntity;
  nth(n: number): SequenceEntity;
  create(entity: Sequence): Promise<void>;
  [n: number]: SequenceEntity;
};

// ── DataRoot ─────────────────────────────────────────────────────────────────

/** Typed root for the pult:data context. Every field maps to a live path proxy. */
export type DataRoot = {
  cues: CueCollection;
  fixtures: FixtureCollection;
  fixture_types: FixtureTypeCollection;
  sequences: SequenceCollection;
  show: PathProxy<Show | null>;
};

/** Create the typed root proxy. The runtime proxy handles all DataRoot operations generically. */
export function createRootProxy(client: PultWsClient): DataRoot {
  return createDataProxy(client) as unknown as DataRoot;
}
