// Auto-generated by pult-codegen — do not edit manually.
// Run: cargo run -p pult-codegen -- generate

import type { PathProxy, SubscribeOptions } from './proxy.js';
import type { PultWsClient } from './client.js';
import { createDataProxy } from './proxy.js';
import type { Cue } from '../generated/Cue.js';
import type { Fixture } from '../generated/Fixture.js';
import type { FixtureType } from '../generated/FixtureType.js';
import type { Flow } from '../generated/Flow.js';
import type { FlowEdge } from '../generated/FlowEdge.js';
import type { FlowNode } from '../generated/FlowNode.js';
import type { OutputConfig } from '../generated/OutputConfig.js';
import type { Sequence } from '../generated/Sequence.js';
import type { Show } from '../generated/Show.js';
import type { Station } from '../generated/Station.js';

// ── Entity handles ───────────────────────────────────────────────────────────

export type CueEntity = PathProxy<Cue> & {
  delete(): Promise<void>;
};

export type FixtureEntity = PathProxy<Fixture> & {
  delete(): Promise<void>;
};

export type FixtureTypeEntity = PathProxy<FixtureType> & {
  delete(): Promise<void>;
};

export type FlowEntity = PathProxy<Flow> & {
  delete(): Promise<void>;
};

export type FlowEdgeEntity = PathProxy<FlowEdge> & {
  delete(): Promise<void>;
};

export type FlowNodeEntity = PathProxy<FlowNode> & {
  delete(): Promise<void>;
  press(): Promise<void>;
};

export type OutputConfigEntity = PathProxy<OutputConfig> & {
  delete(): Promise<void>;
};

export type SequenceEntity = PathProxy<Sequence> & {
  delete(): Promise<void>;
  goNext(): Promise<void>;
  goToCue(args: { cueId: string }): Promise<void>;
};

export type StationEntity = PathProxy<Station> & {
  delete(): Promise<void>;
};

// ── Collection handles ──────────────────────────────────────────────────────

export type CueCollection = {
  get(): Promise<Cue[]>;
  set(value: Cue[]): Promise<void>;
  subscribe(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Cue[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): CueEntity;
  nth(n: number): CueEntity;
  create(entity: Cue): Promise<void>;
  [n: number]: CueEntity;
};

export type FixtureCollection = {
  get(): Promise<Fixture[]>;
  set(value: Fixture[]): Promise<void>;
  subscribe(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Fixture[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureEntity;
  nth(n: number): FixtureEntity;
  create(entity: Fixture): Promise<void>;
  [n: number]: FixtureEntity;
};

export type FixtureTypeCollection = {
  get(): Promise<FixtureType[]>;
  set(value: FixtureType[]): Promise<void>;
  subscribe(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FixtureType[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FixtureTypeEntity;
  nth(n: number): FixtureTypeEntity;
  create(entity: FixtureType): Promise<void>;
  [n: number]: FixtureTypeEntity;
};

export type FlowCollection = {
  get(): Promise<Flow[]>;
  set(value: Flow[]): Promise<void>;
  subscribe(cb: (value: Flow[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Flow[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowEntity;
  nth(n: number): FlowEntity;
  create(entity: Flow): Promise<void>;
  [n: number]: FlowEntity;
};

export type FlowEdgeCollection = {
  get(): Promise<FlowEdge[]>;
  set(value: FlowEdge[]): Promise<void>;
  subscribe(cb: (value: FlowEdge[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FlowEdge[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowEdgeEntity;
  nth(n: number): FlowEdgeEntity;
  create(entity: FlowEdge): Promise<void>;
  [n: number]: FlowEdgeEntity;
};

export type FlowNodeCollection = {
  get(): Promise<FlowNode[]>;
  set(value: FlowNode[]): Promise<void>;
  subscribe(cb: (value: FlowNode[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: FlowNode[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): FlowNodeEntity;
  nth(n: number): FlowNodeEntity;
  create(entity: FlowNode): Promise<void>;
  [n: number]: FlowNodeEntity;
};

export type OutputConfigCollection = {
  get(): Promise<OutputConfig[]>;
  set(value: OutputConfig[]): Promise<void>;
  subscribe(cb: (value: OutputConfig[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: OutputConfig[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): OutputConfigEntity;
  nth(n: number): OutputConfigEntity;
  create(entity: OutputConfig): Promise<void>;
  [n: number]: OutputConfigEntity;
};

export type SequenceCollection = {
  get(): Promise<Sequence[]>;
  set(value: Sequence[]): Promise<void>;
  subscribe(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Sequence[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): SequenceEntity;
  nth(n: number): SequenceEntity;
  create(entity: Sequence): Promise<void>;
  [n: number]: SequenceEntity;
};

export type StationCollection = {
  get(): Promise<Station[]>;
  set(value: Station[]): Promise<void>;
  subscribe(cb: (value: Station[]) => void, opts?: SubscribeOptions): () => void;
  subscribeDeep(cb: (value: Station[]) => void, opts?: SubscribeOptions): () => void;
  byId(id: string): StationEntity;
  nth(n: number): StationEntity;
  create(entity: Station): Promise<void>;
  [n: number]: StationEntity;
};

// ── DataRoot ─────────────────────────────────────────────────────────────────

/** Typed root for the pult:data context. Every field maps to a live path proxy. */
export type DataRoot = {
  cues: CueCollection;
  fixtures: FixtureCollection;
  fixture_types: FixtureTypeCollection;
  flows: FlowCollection;
  flow_edges: FlowEdgeCollection;
  flow_nodes: FlowNodeCollection;
  outputs: OutputConfigCollection;
  sequences: SequenceCollection;
  show: PathProxy<Show | null>;
  stations: StationCollection;
};

/** Create the typed root proxy. The runtime proxy handles all DataRoot operations generically. */
export function createRootProxy(client: PultWsClient): DataRoot {
  return createDataProxy(client) as unknown as DataRoot;
}
