// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { PathPattern } from "./PathPattern";
import type { PathSegment } from "./PathSegment";

/**
 * Messages sent from a frontend client to the backend.
 */
export type ClientMessage = { "type": "Subscribe", "payload": { pattern: PathPattern, } } | { "type": "Unsubscribe", "payload": { pattern: PathPattern, } } | { "type": "Get", "payload": { path: Array<PathSegment>, request_id: string, } } | { "type": "Set", "payload": { path: Array<PathSegment>, value: JsonValue, request_id: string, } } | { "type": "Call", "payload": { method: string, args: JsonValue, request_id: string, } } | { "type": "Ping" };
