// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowMode } from "./FollowMode";
import type { ParameterCapture } from "./ParameterCapture";

/**
 * A single lighting state snapshot with timing information.
 */
export type Cue = { id: string, name: string, 
/**
 * Fractional cue number (1.0, 1.5, 2.0) — allows insertions.
 */
number: number, captures: Array<ParameterCapture>, follow_mode: FollowMode, fade_in_ms: number, fade_out_ms: number, 
/**
 * True when this cue is currently being executed (output is active).
 */
is_active: boolean, };
