// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowMode } from "./FollowMode";
import type { ParameterCapture } from "./ParameterCapture";

export type CueCreate = { name: string, number: number, captures: Array<ParameterCapture>, follow_mode: FollowMode, fade_in_ms: number, fade_out_ms: number, };
