// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowMode } from "./FollowMode";
import type { ParameterCapture } from "./ParameterCapture";

export type CuePatch = { id: string | null, name: string | null, number: number | null, captures: Array<ParameterCapture> | null, follow_mode: FollowMode | null, fade_in_ms: number | null, fade_out_ms: number | null, is_active: boolean | null, };
