// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session discovered on the local network via mDNS.
 */
export type DiscoveredSession = { session_id: string, show_id: string, show_name: string, 
/**
 * Sync endpoint as "ip:port" string.
 */
sync_addr: string, };
