// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterValue } from "./ParameterValue";

/**
 * A patched fixture instance — a specific unit in the rig.
 */
export type Fixture = { id: string, name: string, fixture_type_id: string, universe: number, dmx_address: number, live_values: { [key in string]?: ParameterValue }, active_preset: string | null, };
