// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FixtureCreate = { name: string, fixture_type_id: string, universe: number, dmx_address: number, };
