// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterDefinition } from "./ParameterDefinition";

export type FixtureTypePatch = { id: string | null, name: string | null, manufacturer: string | null, channel_count: number | null, parameters: Array<ParameterDefinition> | null, };
