// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterDefinition } from "./ParameterDefinition";

export type FixtureTypeCreate = { name: string, manufacturer: string, channel_count: number, parameters: Array<ParameterDefinition>, };
