// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterValue } from "./ParameterValue";

export type FixturePatch = { id: string | null, name: string | null, fixture_type_id: string | null, universe: number | null, dmx_address: number | null, live_values: { [key in string]?: ParameterValue } | null, active_preset: string | null | null, };
