// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FollowMode = "Manual" | { "FollowAfter": { delay_ms: number, } } | { "Timecode": { hours: number, minutes: number, seconds: number, frames: number, } };
