// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterKind } from "./ParameterKind";
import type { ParameterValue } from "./ParameterValue";

export type ParameterCapture = { fixture_id: string, parameter_kind: ParameterKind, value: ParameterValue, fade_in_ms: number, fade_out_ms: number, delay_in_ms: number, };
