// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterKind } from "./ParameterKind";
import type { ParameterValue } from "./ParameterValue";

export type ParameterDefinition = { kind: ParameterKind, dmx_channel: number, default_value: ParameterValue, };
