// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A peer console node discovered via mDNS.
 * All fields are LOCAL: visible to connected frontends, not persisted, not synced to peers.
 */
export type PeerInfo = { id: string, name: string, address: string, last_seen: string, is_connected: boolean, };
