// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ordered list of cues (called a "sequence" by the operator).
 */
export type Sequence = { id: string, name: string, 
/**
 * Ordered list of cue IDs belonging to this sequence.
 */
cue_ids: Array<string>, 
/**
 * Index of the currently active cue within cue_ids, if any.
 */
active_cue_index: number | null, };
