// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SequencePatch = { id: string | null, name: string | null, cue_ids: Array<string> | null, active_cue_index: number | null | null, };
