// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { PathSegment } from "./PathSegment";

/**
 * Messages sent from the backend to a frontend client.
 */
export type ServerMessage = { "type": "GetResult", "payload": { path: Array<PathSegment>, value: JsonValue, request_id: string, } } | { "type": "SetAck", "payload": { request_id: string, ok: boolean, error: string | null, } } | { "type": "CallResult", "payload": { request_id: string, result: JsonValue | null, error: string | null, } } | { "type": "Update", "payload": { path: Array<PathSegment>, value: JsonValue, } } | { "type": "Error", "payload": { message: string, } } | { "type": "Pong" };
