// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveredSession } from "./DiscoveredSession";

/**
 * The local node's session state — LOCAL lifecycle:
 * broadcast to connected frontends but not persisted or synced to peers.
 * The engine holds this as `ShowState.session`; the SessionManager is the only writer.
 */
export type SessionState = { is_advertising: boolean, is_follower: boolean, session_id: string | null, discovered: Array<DiscoveredSession>, };
