// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShowPatch = { id: string | null, name: string | null, created_at: string | null, is_running: boolean | null, active_sequence: string | null | null, };
