// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level show metadata.
 */
export type Show = { id: string, name: string, created_at: string, 
/**
 * Whether the show engine is actively running.
 */
is_running: boolean, 
/**
 * ID of the currently active sequence, if any.
 */
active_sequence: string | null, };
